## 从PMLR补充缺失的数据

In [ ]:
import re
import time
import random
from pathlib import Path
from urllib.parse import urljoin
from difflib import get_close_matches

import pandas as pd
import requests
from bs4 import BeautifulSoup


INPUT_CSV = Path(
    "/home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/"
    "Data/20260708_openalex/icml_unmatched_dblp_papers.csv"
)

OUT_CSV = Path("/home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/"
               "Data/20260710_pmlr/icml_unmatched_with_pmlr_url_all_tracks.csv")
    
OUT_UNMATCHED_CSV =  Path("/home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/"
                          "Data/20260710_pmlr/icml_unmatched_still_no_pmlr_url_all_tracks.csv")


ICML_MAIN_PMLR_VOLUMES = {
    2020: 119,
    2021: 139,
    2022: 162,
    2023: 202,
    2024: 235,
    2025: 267,
}


def normalize_title(title):
    title = str(title or "").lower()
    title = title.replace("&amp;", " and ")
    title = title.replace("&", " and ")
    title = re.sub(r"[^a-z0-9]+", " ", title)
    title = re.sub(r"\s+", " ", title).strip()
    return title


def clean_text(text):
    return re.sub(r"\s+", " ", str(text or "")).strip()


def request_with_retry(url, n_retry=4):
    headers = {"User-Agent": "Mozilla/5.0"}

    last_error = None
    for attempt in range(1, n_retry + 1):
        try:
            r = requests.get(url, headers=headers, timeout=30)
            r.raise_for_status()
            return r.text
        except Exception as exc:
            last_error = exc
            wait = attempt * 1.5 + random.uniform(0, 1)
            print(f"[Retry {attempt}/{n_retry}] {url}: {exc}; wait {wait:.1f}s")
            time.sleep(wait)

    raise RuntimeError(f"Failed to fetch {url}: {last_error}")


def parse_pmlr_volume(year, volume):
    volume_url = f"https://proceedings.mlr.press/v{volume}/"
    html = request_with_retry(volume_url)
    soup = BeautifulSoup(html, "html.parser")

    rows = []

    for paper in soup.select("div.paper"):
        title_node = paper.select_one("p.title")
        if title_node is None:
            continue

        title = clean_text(title_node.get_text(" ", strip=True))
        if not title:
            continue

        pmlr_url = ""

        for a in paper.find_all("a", href=True):
            label = clean_text(a.get_text(" ", strip=True)).lower()
            href = a["href"]

            if label == "abs" or href.endswith(".html"):
                pmlr_url = urljoin(volume_url, href)
                break

        rows.append({
            "year": year,
            "pmlr_volume": volume,
            "pmlr_title": title,
            "pmlr_title_norm": normalize_title(title),
            "pmlr_url": pmlr_url,
            "pmlr_volume_url": volume_url,
            "pmlr_source": "main_pmlr_volume",
        })

    return pd.DataFrame(rows)


def extract_title_from_dblp_li(li):
    node = li.find("span", class_="title")
    if node is None:
        return ""
    return clean_text(node.get_text(" ", strip=True)).rstrip(".")


def extract_external_links_from_dblp_li(li):
    links = []

    for a in li.find_all("a", href=True):
        href = a["href"].strip()
        label = clean_text(a.get_text(" ", strip=True)).lower()

        if not href.startswith("http"):
            continue

        link_type = "other"
        if "proceedings.mlr.press" in href:
            link_type = "pmlr"
        elif "doi.org" in href:
            link_type = "doi"
        elif "openreview.net" in href:
            link_type = "openreview"
        elif "link.springer.com" in href:
            link_type = "springer"

        links.append({
            "label": label,
            "url": href,
            "link_type": link_type,
        })

    return links


def parse_dblp_source_page(source_url):
    html = request_with_retry(source_url)
    soup = BeautifulSoup(html, "html.parser")

    rows = []

    for li in soup.select("li.entry.inproceedings"):
        title = extract_title_from_dblp_li(li)
        if not title:
            continue

        links = extract_external_links_from_dblp_li(li)

        pmlr_links = [x["url"] for x in links if x["link_type"] == "pmlr"]
        doi_links = [x["url"] for x in links if x["link_type"] == "doi"]
        openreview_links = [x["url"] for x in links if x["link_type"] == "openreview"]
        springer_links = [x["url"] for x in links if x["link_type"] == "springer"]

        rows.append({
            "dblp_source_url": source_url,
            "dblp_title": title,
            "dblp_title_norm": normalize_title(title),
            "dblp_pmlr_url": pmlr_links[0] if pmlr_links else "",
            "dblp_doi_url": doi_links[0] if doi_links else "",
            "dblp_openreview_url": openreview_links[0] if openreview_links else "",
            "dblp_springer_url": springer_links[0] if springer_links else "",
        })

    return pd.DataFrame(rows)


# =========================
# 1. Load unmatched ICML papers
# =========================
df = pd.read_csv(INPUT_CSV)
df["title_norm_for_match"] = df["title"].map(normalize_title)

df["pmlr_url"] = ""
df["pmlr_title"] = ""
df["pmlr_volume"] = ""
df["pmlr_match_method"] = "not_processed"
df["external_url_from_dblp"] = ""
df["external_url_type_from_dblp"] = ""


# =========================
# 2. Main track: match by ICML main PMLR volume
# =========================
pmlr_main_dfs = []

for year, volume in ICML_MAIN_PMLR_VOLUMES.items():
    print(f"Parsing ICML main proceedings {year}: PMLR v{volume}")
    pmlr_main_dfs.append(parse_pmlr_volume(year, volume))
    time.sleep(random.uniform(0.4, 0.9))

pmlr_main_df = pd.concat(pmlr_main_dfs, ignore_index=True)

main_index = {
    (int(row["year"]), row["pmlr_title_norm"]): row
    for _, row in pmlr_main_df.iterrows()
}

main_mask = df["track_type"].eq("main_track")

for idx, row in df[main_mask].iterrows():
    year = int(row["year"])
    title_norm = row["title_norm_for_match"]

    match = main_index.get((year, title_norm))

    if match is not None:
        df.loc[idx, "pmlr_url"] = match["pmlr_url"]
        df.loc[idx, "pmlr_title"] = match["pmlr_title"]
        df.loc[idx, "pmlr_volume"] = match["pmlr_volume"]
        df.loc[idx, "pmlr_match_method"] = "main_track_exact_title"
    else:
        df.loc[idx, "pmlr_match_method"] = "main_track_unmatched_exact"


# Fuzzy matching for main track
for year in sorted(df.loc[main_mask, "year"].dropna().unique()):
    year = int(year)

    candidates = pmlr_main_df[pmlr_main_df["year"] == year].copy()
    candidate_titles = candidates["pmlr_title_norm"].tolist()
    candidate_map = {
        row["pmlr_title_norm"]: row
        for _, row in candidates.iterrows()
    }

    fuzzy_mask = (
        df["track_type"].eq("main_track")
        & (df["year"].astype(int) == year)
        & df["pmlr_match_method"].eq("main_track_unmatched_exact")
    )

    for idx, row in df[fuzzy_mask].iterrows():
        query = row["title_norm_for_match"]
        close = get_close_matches(query, candidate_titles, n=1, cutoff=0.96)

        if close:
            best = candidate_map[close[0]]
            df.loc[idx, "pmlr_url"] = best["pmlr_url"]
            df.loc[idx, "pmlr_title"] = best["pmlr_title"]
            df.loc[idx, "pmlr_volume"] = best["pmlr_volume"]
            df.loc[idx, "pmlr_match_method"] = "main_track_fuzzy_title"


# =========================
# 3. Non-main track: parse each DBLP source_url
# =========================
non_main_mask = df["track_type"].eq("non-main_track")
source_urls = sorted(df.loc[non_main_mask, "source_url"].dropna().unique())

dblp_source_dfs = []

for source_url in source_urls:
    print(f"Parsing non-main DBLP source page: {source_url}")
    source_df = parse_dblp_source_page(source_url)
    source_df["source_url"] = source_url
    dblp_source_dfs.append(source_df)
    time.sleep(random.uniform(0.4, 0.9))

if dblp_source_dfs:
    dblp_source_df = pd.concat(dblp_source_dfs, ignore_index=True)
else:
    dblp_source_df = pd.DataFrame()


# Exact title matching within each non-main source_url
if not dblp_source_df.empty:
    non_main_index = {
        (row["source_url"], row["dblp_title_norm"]): row
        for _, row in dblp_source_df.iterrows()
    }

    for idx, row in df[non_main_mask].iterrows():
        key = (row["source_url"], row["title_norm_for_match"])
        match = non_main_index.get(key)

        if match is None:
            df.loc[idx, "pmlr_match_method"] = "non_main_unmatched_exact"
            continue

        pmlr_url = match.get("dblp_pmlr_url", "")
        doi_url = match.get("dblp_doi_url", "")
        openreview_url = match.get("dblp_openreview_url", "")
        springer_url = match.get("dblp_springer_url", "")

        df.loc[idx, "pmlr_title"] = match["dblp_title"]

        if pmlr_url:
            df.loc[idx, "pmlr_url"] = pmlr_url
            df.loc[idx, "pmlr_match_method"] = "non_main_dblp_pmlr_exact_title"
            df.loc[idx, "external_url_from_dblp"] = pmlr_url
            df.loc[idx, "external_url_type_from_dblp"] = "pmlr"
        elif openreview_url:
            df.loc[idx, "external_url_from_dblp"] = openreview_url
            df.loc[idx, "external_url_type_from_dblp"] = "openreview"
            df.loc[idx, "pmlr_match_method"] = "non_main_no_pmlr_but_openreview"
        elif springer_url:
            df.loc[idx, "external_url_from_dblp"] = springer_url
            df.loc[idx, "external_url_type_from_dblp"] = "springer"
            df.loc[idx, "pmlr_match_method"] = "non_main_no_pmlr_but_springer"
        elif doi_url:
            df.loc[idx, "external_url_from_dblp"] = doi_url
            df.loc[idx, "external_url_type_from_dblp"] = "doi"
            df.loc[idx, "pmlr_match_method"] = "non_main_no_pmlr_but_doi"
        else:
            df.loc[idx, "pmlr_match_method"] = "non_main_exact_title_no_external_url"


# Fuzzy matching for non-main source pages
if not dblp_source_df.empty:
    for source_url in source_urls:
        candidates = dblp_source_df[dblp_source_df["source_url"] == source_url].copy()
        candidate_titles = candidates["dblp_title_norm"].tolist()
        candidate_map = {
            row["dblp_title_norm"]: row
            for _, row in candidates.iterrows()
        }

        fuzzy_mask = (
            df["track_type"].eq("non-main_track")
            & df["source_url"].eq(source_url)
            & df["pmlr_match_method"].isin([
                "non_main_unmatched_exact",
                "not_processed",
            ])
        )

        for idx, row in df[fuzzy_mask].iterrows():
            query = row["title_norm_for_match"]
            close = get_close_matches(query, candidate_titles, n=1, cutoff=0.96)

            if not close:
                df.loc[idx, "pmlr_match_method"] = "non_main_still_unmatched"
                continue

            best = candidate_map[close[0]]

            pmlr_url = best.get("dblp_pmlr_url", "")
            doi_url = best.get("dblp_doi_url", "")
            openreview_url = best.get("dblp_openreview_url", "")
            springer_url = best.get("dblp_springer_url", "")

            df.loc[idx, "pmlr_title"] = best["dblp_title"]

            if pmlr_url:
                df.loc[idx, "pmlr_url"] = pmlr_url
                df.loc[idx, "pmlr_match_method"] = "non_main_dblp_pmlr_fuzzy_title"
                df.loc[idx, "external_url_from_dblp"] = pmlr_url
                df.loc[idx, "external_url_type_from_dblp"] = "pmlr"
            elif openreview_url:
                df.loc[idx, "external_url_from_dblp"] = openreview_url
                df.loc[idx, "external_url_type_from_dblp"] = "openreview"
                df.loc[idx, "pmlr_match_method"] = "non_main_fuzzy_no_pmlr_but_openreview"
            elif springer_url:
                df.loc[idx, "external_url_from_dblp"] = springer_url
                df.loc[idx, "external_url_type_from_dblp"] = "springer"
                df.loc[idx, "pmlr_match_method"] = "non_main_fuzzy_no_pmlr_but_springer"
            elif doi_url:
                df.loc[idx, "external_url_from_dblp"] = doi_url
                df.loc[idx, "external_url_type_from_dblp"] = "doi"
                df.loc[idx, "pmlr_match_method"] = "non_main_fuzzy_no_pmlr_but_doi"
            else:
                df.loc[idx, "pmlr_match_method"] = "non_main_fuzzy_title_no_external_url"


# =========================
# 4. Save
# =========================
df.to_csv(OUT_CSV, index=False, encoding="utf-8-sig")

still_no_pmlr = df[
    df["pmlr_url"].isna() | (df["pmlr_url"].astype(str).str.len() == 0)
].copy()

still_no_pmlr.to_csv(OUT_UNMATCHED_CSV, index=False, encoding="utf-8-sig")

print("Total:", len(df))
print("\nPMLR match method counts:")
print(df["pmlr_match_method"].value_counts(dropna=False))

print("\nExternal URL type counts for non-main:")
print(df.loc[df["track_type"].eq("non-main_track"), "external_url_type_from_dblp"].value_counts(dropna=False))

print("\nSaved:", OUT_CSV)
print("Saved still no PMLR:", OUT_UNMATCHED_CSV)

Parsing ICML main proceedings 2020: PMLR v119
Parsing ICML main proceedings 2021: PMLR v139
Parsing ICML main proceedings 2022: PMLR v162
Parsing ICML main proceedings 2023: PMLR v202
Parsing ICML main proceedings 2024: PMLR v235
Parsing ICML main proceedings 2025: PMLR v267
Parsing non-main DBLP source page: https://dblp.org/db/conf/icml/hcai2022.html
Parsing non-main DBLP source page: https://dblp.org/db/conf/icml/icml2025p.html
Parsing non-main DBLP source page: https://dblp.org/db/conf/icml/terrabytes2025.html
Parsing non-main DBLP source page: https://dblp.org/db/conf/icml/xxai2020.html
Total: 3044

PMLR match method counts:
pmlr_match_method
main_track_exact_title            2869
non_main_dblp_pmlr_exact_title      98
main_track_fuzzy_title              41
main_track_unmatched_exact          18
non_main_no_pmlr_but_doi            18
Name: count, dtype: int64

External URL type counts for non-main:
external_url_type_from_dblp
pmlr    98
doi     18
Name: count, dtype: int64

Saved: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260708_openalex/icml_unmatched_with_pmlr_url_all_tracks.csv
Saved still no PMLR: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260708_openalex/icml_unmatched_still_no_pmlr_url_all_tracks.csv

In [ ]:
import re
import json
import time
import random
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed

import pandas as pd
import requests
from bs4 import BeautifulSoup


# =========================
# Paths
# =========================
INPUT_CSV = Path(
    "/home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/"
    "Data/20260710_pmlr/icml_unmatched_with_pmlr_url_all_tracks.csv"
)

OUT_CSV = INPUT_CSV.with_name("icml_unmatched_with_pmlr_abstract.csv")
OUT_SUCCESS_CSV = INPUT_CSV.with_name("icml_pmlr_abstract_success.csv")
OUT_FAILED_CSV = INPUT_CSV.with_name("icml_pmlr_abstract_failed.csv")
CACHE_JSONL = INPUT_CSV.with_name("icml_pmlr_abstract_cache.jsonl")


# =========================
# Config
# =========================
MAX_WORKERS = 8
N_RETRY = 4
REQUEST_TIMEOUT = 30


# =========================
# Helpers
# =========================
def clean_text(text):
    text = re.sub(r"\s+", " ", str(text or "")).strip()
    text = re.sub(r"^Abstract\s+", "", text, flags=re.IGNORECASE).strip()
    return text


def parse_pmlr_abstract_from_html(html_text):
    soup = BeautifulSoup(html_text, "html.parser")

    # 方法1：PMLR 页面通常有 h4/h3: Abstract
    for header in soup.find_all(["h2", "h3", "h4", "h5"]):
        if clean_text(header.get_text(" ", strip=True)).lower() == "abstract":
            parts = []

            for sib in header.next_siblings:
                if getattr(sib, "name", None) in ["h2", "h3", "h4", "h5"]:
                    break

                if hasattr(sib, "get_text"):
                    text = clean_text(sib.get_text(" ", strip=True))
                else:
                    text = clean_text(str(sib))

                if text:
                    parts.append(text)

            abstract = clean_text(" ".join(parts))
            if len(abstract.split()) >= 10:
                return abstract

    # 方法2：有些页面可能把 abstract 放在 meta 字段里
    for meta_name in ["citation_abstract", "description"]:
        meta = soup.find("meta", attrs={"name": meta_name})
        if meta and meta.get("content"):
            abstract = clean_text(meta.get("content"))
            if len(abstract.split()) >= 10:
                return abstract

    # 方法3：从 BibTeX block 中尝试解析 abstract 字段
    text = soup.get_text("\n", strip=True)
    match = re.search(
        r"abstract\s*=\s*[{\"'](.+?)[}\"']\s*,?\s*\n",
        text,
        flags=re.IGNORECASE | re.DOTALL
    )
    if match:
        abstract = clean_text(match.group(1))
        if len(abstract.split()) >= 10:
            return abstract

    return ""


def fetch_pmlr_abstract(url):
    headers = {"User-Agent": "Mozilla/5.0"}
    last_error = ""

    for attempt in range(1, N_RETRY + 1):
        try:
            time.sleep(random.uniform(0.1, 0.4))
            r = requests.get(url, headers=headers, timeout=REQUEST_TIMEOUT)

            if r.status_code == 200:
                abstract = parse_pmlr_abstract_from_html(r.text)

                if abstract:
                    return {
                        "pmlr_url": url,
                        "status": "success",
                        "abstract": abstract,
                        "error": "",
                    }

                return {
                    "pmlr_url": url,
                    "status": "no_abstract_on_page",
                    "abstract": "",
                    "error": "",
                }

            if r.status_code == 404:
                return {
                    "pmlr_url": url,
                    "status": "not_found",
                    "abstract": "",
                    "error": "404",
                }

            last_error = f"HTTP {r.status_code}: {r.text[:200]}"

            if r.status_code in {429, 500, 502, 503, 504}:
                wait = min(60, 2 ** attempt + random.uniform(0, 2))
                time.sleep(wait)
                continue

            return {
                "pmlr_url": url,
                "status": "http_error",
                "abstract": "",
                "error": last_error,
            }

        except Exception as exc:
            last_error = repr(exc)
            wait = min(60, 2 ** attempt + random.uniform(0, 2))
            time.sleep(wait)

    return {
        "pmlr_url": url,
        "status": "request_failed",
        "abstract": "",
        "error": last_error,
    }


def load_cache(cache_path):
    cache = {}

    if not cache_path.exists():
        return cache

    with cache_path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            try:
                obj = json.loads(line)
            except Exception:
                continue

            url = obj.get("pmlr_url")
            if url:
                cache[url] = obj

    return cache


def append_cache(cache_path, obj):
    with cache_path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(obj, ensure_ascii=False) + "\n")


# =========================
# 1. Load data
# =========================
df = pd.read_csv(INPUT_CSV)

df["pmlr_url"] = df["pmlr_url"].fillna("").astype(str).str.strip()

target_urls = sorted(
    url for url in df["pmlr_url"].unique()
    if url.startswith("http") and "proceedings.mlr.press" in url
)

print("Total rows:", len(df))
print("Rows with PMLR URL:", (df["pmlr_url"].str.len() > 0).sum())
print("Unique PMLR URLs:", len(target_urls))


# =========================
# 2. Load cache
# =========================
cache = load_cache(CACHE_JSONL)
print("Cached URLs:", len(cache))

to_fetch = [
    url for url in target_urls
    if url not in cache or cache[url].get("status") in {
        "request_failed", "http_error"
    }
]

print("Need to fetch:", len(to_fetch))


# =========================
# 3. Fetch abstracts
# =========================
if to_fetch:
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        future_map = {
            executor.submit(fetch_pmlr_abstract, url): url
            for url in to_fetch
        }

        for i, fut in enumerate(as_completed(future_map), start=1):
            url = future_map[fut]

            try:
                result = fut.result()
            except Exception as exc:
                result = {
                    "pmlr_url": url,
                    "status": "request_exception",
                    "abstract": "",
                    "error": repr(exc),
                }

            cache[url] = result
            append_cache(CACHE_JSONL, result)

            if i % 100 == 0 or i == len(to_fetch):
                status_counts = pd.Series(
                    [x.get("status") for x in cache.values()]
                ).value_counts(dropna=False).to_dict()
                print(f"Fetched {i}/{len(to_fetch)} | statuses: {status_counts}")


# =========================
# 4. Attach abstracts back to rows
# =========================
df["pmlr_abstract"] = ""
df["pmlr_abstract_status"] = ""
df["pmlr_abstract_error"] = ""
df["pmlr_abstract_words"] = 0

for idx, row in df.iterrows():
    url = row["pmlr_url"]

    if not url:
        df.loc[idx, "pmlr_abstract_status"] = "missing_pmlr_url"
        continue

    item = cache.get(url)

    if item is None:
        df.loc[idx, "pmlr_abstract_status"] = "not_in_cache"
        continue

    abstract = item.get("abstract", "") or ""

    df.loc[idx, "pmlr_abstract"] = abstract
    df.loc[idx, "pmlr_abstract_status"] = item.get("status", "")
    df.loc[idx, "pmlr_abstract_error"] = item.get("error", "")
    df.loc[idx, "pmlr_abstract_words"] = len(abstract.split())


# =========================
# 5. Save
# =========================
df.to_csv(OUT_CSV, index=False, encoding="utf-8-sig")

success_df = df[df["pmlr_abstract_status"].eq("success")].copy()
failed_df = df[~df["pmlr_abstract_status"].eq("success")].copy()

success_df.to_csv(OUT_SUCCESS_CSV, index=False, encoding="utf-8-sig")
failed_df.to_csv(OUT_FAILED_CSV, index=False, encoding="utf-8-sig")


print("\nAbstract status counts:")
print(df["pmlr_abstract_status"].value_counts(dropna=False))

print("\nSaved full file:", OUT_CSV)
print("Saved success file:", OUT_SUCCESS_CSV)
print("Saved failed file:", OUT_FAILED_CSV)
print("Saved cache:", CACHE_JSONL)

Total rows: 3044
Rows with PMLR URL: 3008
Unique PMLR URLs: 3008
Cached URLs: 0
Need to fetch: 3008
Fetched 100/3008 | statuses: {'success': 100}
Fetched 200/3008 | statuses: {'success': 200}
Fetched 300/3008 | statuses: {'success': 300}
Fetched 400/3008 | statuses: {'success': 400}
Fetched 500/3008 | statuses: {'success': 500}
Fetched 600/3008 | statuses: {'success': 600}
Fetched 700/3008 | statuses: {'success': 700}
Fetched 800/3008 | statuses: {'success': 800}
Fetched 900/3008 | statuses: {'success': 900}
Fetched 1000/3008 | statuses: {'success': 1000}
Fetched 1100/3008 | statuses: {'success': 1100}
Fetched 1200/3008 | statuses: {'success': 1200}
Fetched 1300/3008 | statuses: {'success': 1300}
Fetched 1400/3008 | statuses: {'success': 1400}
Fetched 1500/3008 | statuses: {'success': 1500}
Fetched 1600/3008 | statuses: {'success': 1600}
Fetched 1700/3008 | statuses: {'success': 1700}
Fetched 1800/3008 | statuses: {'success': 1800}
Fetched 1900/3008 | statuses: {'success': 1900}
Fetched 2000/3008 | statuses: {'success': 2000}
Fetched 2100/3008 | statuses: {'success': 2100}
Fetched 2200/3008 | statuses: {'success': 2200}
Fetched 2300/3008 | statuses: {'success': 2300}
Fetched 2400/3008 | statuses: {'success': 2400}
Fetched 2500/3008 | statuses: {'success': 2500}
Fetched 2600/3008 | statuses: {'success': 2600}
Fetched 2700/3008 | statuses: {'success': 2700}
Fetched 2800/3008 | statuses: {'success': 2800}
Fetched 2900/3008 | statuses: {'success': 2900}
Fetched 3000/3008 | statuses: {'success': 3000}
Fetched 3008/3008 | statuses: {'success': 3008}

Abstract status counts:
pmlr_abstract_status
success             3008
missing_pmlr_url      36
Name: count, dtype: int64

Saved full file: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260710_pmlr_iclr/icml_unmatched_with_pmlr_abstract.csv
Saved success file: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260710_pmlr_iclr/icml_pmlr_abstract_success.csv
Saved failed file: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260710_pmlr_iclr/icml_pmlr_abstract_failed.csv
Saved cache: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260710_pmlr_iclr/icml_pmlr_abstract_cache.jsonl

### 从open review补充iclr tiny papers的摘要

In [1]:
import re
import html
import time
import random
from pathlib import Path
from urllib.parse import urlparse, parse_qs

import pandas as pd
import requests
from bs4 import BeautifulSoup


# =========================
# Config
# =========================
BASE_DIR = Path("/home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data")
OUT_DIR = BASE_DIR / "20260712_iclr_tiny_openreview"
OUT_DIR.mkdir(parents=True, exist_ok=True)

DBLP_TINY_URLS = {
    2023: "https://dblp.org/db/conf/iclr/iclr2023tiny.html",
    2024: "https://dblp.org/db/conf/iclr/iclr2024tiny.html",
}

OUT_CSV = OUT_DIR / "iclr_tiny_papers_openreview_links.csv"


# =========================
# Helpers
# =========================
def normalize_text(text):
    text = html.unescape(str(text or ""))
    text = re.sub(r"\s+", " ", text).strip()
    return text


def request_with_retry(url, n_retry=5, sleep_base=1.5):
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/126.0 Safari/537.36"
        )
    }

    last_error = None

    for attempt in range(1, n_retry + 1):
        try:
            response = requests.get(url, headers=headers, timeout=40)
            response.raise_for_status()
            return response.text
        except Exception as exc:
            last_error = exc
            wait = sleep_base * attempt + random.uniform(0, 0.8)
            print(f"[Retry] {attempt}/{n_retry} failed for {url}: {exc}; wait {wait:.1f}s")
            time.sleep(wait)

    raise RuntimeError(f"Failed to fetch {url}: {last_error}")


def extract_title(li):
    node = li.select_one("span.title")
    if node:
        return normalize_text(node.get_text(" ", strip=True)).rstrip(".")
    return ""


def extract_authors(li):
    authors = []

    for node in li.select('[itemprop="author"] [itemprop="name"]'):
        name = normalize_text(node.get_text(" ", strip=True))
        if name:
            authors.append(name)

    if not authors:
        for a in li.find_all("a", href=True):
            href = a.get("href", "")
            if "/pid/" in href:
                name = normalize_text(a.get_text(" ", strip=True))
                if name:
                    authors.append(name)

    seen = set()
    out = []

    for name in authors:
        if name not in seen:
            seen.add(name)
            out.append(name)

    return "; ".join(out)


def extract_openreview_url(li):
    for a in li.find_all("a", href=True):
        href = a.get("href", "")
        if "openreview.net/forum" in href:
            return href
    return ""


def extract_openreview_id(openreview_url):
    if not openreview_url:
        return ""

    parsed = urlparse(openreview_url)
    qs = parse_qs(parsed.query)

    if "id" in qs and qs["id"]:
        return qs["id"][0]

    match = re.search(r"id=([^&]+)", openreview_url)
    if match:
        return match.group(1)

    return ""


# =========================
# Collect links
# =========================
rows = []

for year, url in DBLP_TINY_URLS.items():
    print(f"Fetching DBLP Tiny Papers page: {year} {url}")

    html_text = request_with_retry(url)
    soup = BeautifulSoup(html_text, "html.parser")

    entries = soup.select("li.entry.inproceedings")
    print(f"  entries found: {len(entries)}")

    for li in entries:
        title = extract_title(li)
        authors = extract_authors(li)
        openreview_url = extract_openreview_url(li)
        openreview_id = extract_openreview_id(openreview_url)

        rows.append({
            "conference": "ICLR",
            "year": year,
            "track_type": "non-main_track",
            "proceedings_type": "non-main_proceedings",
            "proceedings_name": (
                "The First Tiny Papers Track at ICLR 2023"
                if year == 2023
                else "The Second Tiny Papers Track at ICLR 2024"
            ),
            "title": title,
            "authors": authors,
            "openreview_id": openreview_id,
            "openreview_url": openreview_url,
            "openreview_pdf_url": f"https://openreview.net/pdf?id={openreview_id}" if openreview_id else "",
            "source_url": url,
        })

    time.sleep(random.uniform(0.5, 1.0))


links_df = pd.DataFrame(rows)
links_df = links_df.drop_duplicates(subset=["year", "title", "openreview_id"])
links_df = links_df.sort_values(["year", "title"]).reset_index(drop=True)

links_df.to_csv(OUT_CSV, index=False, encoding="utf-8-sig")

print("=" * 80)
print("ICLR Tiny Papers OpenReview links collected")
print("=" * 80)
print(f"Total rows: {len(links_df)}")
print(f"Rows with OpenReview ID: {links_df['openreview_id'].astype(str).str.len().gt(0).sum()}")
print(f"Saved to: {OUT_CSV}")

display(links_df.head())

Fetching DBLP Tiny Papers page: 2023 https://dblp.org/db/conf/iclr/iclr2023tiny.html
  entries found: 219
Fetching DBLP Tiny Papers page: 2024 https://dblp.org/db/conf/iclr/iclr2024tiny.html
  entries found: 194
================================================================================
ICLR Tiny Papers OpenReview links collected
================================================================================
Total rows: 413
Rows with OpenReview ID: 413
Saved to: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260712_iclr_tiny_openreview/iclr_tiny_papers_openreview_links.csv

,conference,year,track_type,proceedings_type,proceedings_name,title,authors,openreview_id,openreview_url,openreview_pdf_url,source_url
0,ICLR,2023,non-main_track,non-main_proceedings,The First Tiny Papers Track at ICLR 2023,A Brief History of the Speculative Measures fo...,Micah Tewers,qqKO_rrg9y,https://openreview.net/forum?id=qqKO_rrg9y,https://openreview.net/pdf?id=qqKO_rrg9y,https://dblp.org/db/conf/iclr/iclr2023tiny.html
1,ICLR,2023,non-main_track,non-main_proceedings,The First Tiny Papers Track at ICLR 2023,A Change of Heart: Improving Speech Emotion Re...,Zeinab Sadat Taghavi; Ali Satvaty; Hossein Sameti,S9NTReFikL2,https://openreview.net/forum?id=S9NTReFikL2,https://openreview.net/pdf?id=S9NTReFikL2,https://dblp.org/db/conf/iclr/iclr2023tiny.html
2,ICLR,2023,non-main_track,non-main_proceedings,The First Tiny Papers Track at ICLR 2023,A Dynamic Prompt-tuning Method for Data Augmen...,Qianqian Qi; Qiming Bao; Alex Yuxuan Peng; Jia...,hli7A0ioiS_,https://openreview.net/forum?id=hli7A0ioiS_,https://openreview.net/pdf?id=hli7A0ioiS_,https://dblp.org/db/conf/iclr/iclr2023tiny.html
3,ICLR,2023,non-main_track,non-main_proceedings,The First Tiny Papers Track at ICLR 2023,A Light Spectrometer Device for Crop Disease M...,Joshua Jeremy Dhikusooka; Ephraim Nuwamanya; E...,KtVonyo4AS,https://openreview.net/forum?id=KtVonyo4AS,https://openreview.net/pdf?id=KtVonyo4AS,https://dblp.org/db/conf/iclr/iclr2023tiny.html
4,ICLR,2023,non-main_track,non-main_proceedings,The First Tiny Papers Track at ICLR 2023,A Rate-Distortion View on Model Updates,Nicole Mitchell; Johannes Ballé; Zachary Charl...,6ry6ibTKOx,https://openreview.net/forum?id=6ry6ibTKOx,https://openreview.net/pdf?id=6ry6ibTKOx,https://dblp.org/db/conf/iclr/iclr2023tiny.html

In [2]:
import re
import json
import time
import random
import subprocess
from pathlib import Path

import pandas as pd
import requests


# =========================
# Config
# =========================
BASE_DIR = Path("/home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data")
WORK_DIR = BASE_DIR / "20260712_iclr_tiny_openreview"
WORK_DIR.mkdir(parents=True, exist_ok=True)

LINKS_CSV = WORK_DIR / "iclr_tiny_papers_openreview_links.csv"

PDF_DIR = WORK_DIR / "pdfs"
TXT_DIR = WORK_DIR / "txt"
PDF_DIR.mkdir(parents=True, exist_ok=True)
TXT_DIR.mkdir(parents=True, exist_ok=True)

OUT_CSV = WORK_DIR / "iclr_tiny_papers_openreview_abstracts.csv"
OUT_JSONL = WORK_DIR / "iclr_tiny_papers_openreview_abstracts.jsonl"
FAILED_CSV = WORK_DIR / "iclr_tiny_papers_openreview_failed.csv"

# 从浏览器复制 OpenReview Cookie 后填在这里
OPENREVIEW_COOKIE = "_ga=GA1.1.390589554.1753754127; _ga_GTB25PBMVL=GS2.1.s1783837793$o53$g1$t1783838797$j60$l0$h0; openreview.clearanceToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpcCI6IjEwMy4xMzQuMzUuMTAyIiwianRpIjoiMmU4MzNhYzgtZTNlMy00OWQ5LWI2ZjctNDVjNDFjMTlkNmY1IiwiaWF0IjoxNzgzODM4ODEyLCJleHAiOjE3ODM4MzkxMTJ9.7EdBe8WuVEJSdP_69ncQUwNzMwSdZ60aPpQRH4j4dKg"

SLEEP_SECONDS = 0.8
N_RETRY = 4


# =========================
# Helpers
# =========================
def normalize_space(text):
    return re.sub(r"\s+", " ", str(text or "")).strip()


def safe_filename(text):
    text = str(text or "")
    text = re.sub(r"[^a-zA-Z0-9_.-]+", "_", text)
    return text[:120]


def request_pdf_with_cookie(url, cookie, n_retry=4):
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/126.0 Safari/537.36"
        ),
        "Accept": "application/pdf,text/html;q=0.9,*/*;q=0.8",
        "Referer": "https://openreview.net/",
        "Cookie": cookie,
    }

    last_error = ""

    for attempt in range(1, n_retry + 1):
        try:
            response = requests.get(url, headers=headers, timeout=60)

            content_type = response.headers.get("content-type", "").lower()
            content = response.content

            if response.status_code == 200 and content.startswith(b"%PDF"):
                return {
                    "success": True,
                    "status_code": response.status_code,
                    "content_type": content_type,
                    "content": content,
                    "error": "",
                }

            error_msg = (
                f"Non-PDF response. status={response.status_code}, "
                f"content_type={content_type}, first_bytes={content[:80]!r}"
            )

            last_error = error_msg

        except Exception as exc:
            last_error = repr(exc)

        wait = attempt * 1.5 + random.uniform(0, 0.8)
        print(f"[Retry {attempt}/{n_retry}] {url}: {last_error}; wait {wait:.1f}s")
        time.sleep(wait)

    return {
        "success": False,
        "status_code": None,
        "content_type": "",
        "content": b"",
        "error": last_error,
    }


def pdf_to_text(pdf_path, txt_path):
    cmd = [
        "pdftotext",
        "-layout",
        "-f", "1",
        "-l", "2",
        str(pdf_path),
        str(txt_path),
    ]

    result = subprocess.run(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )

    if result.returncode != 0:
        return False, result.stderr

    return True, ""


def extract_abstract_from_text(text):
    """
    适用于大多数 OpenReview PDF。
    抽取 Abstract 到 Introduction / 1 Introduction / Keywords 等之间的文本。
    """
    raw = str(text or "")
    raw = raw.replace("\x0c", "\n")

    patterns = [
        r"(?is)\babstract\b\s*[:.\-]?\s*(.*?)(?:\n\s*1\s+introduction\b|\n\s*1\.\s+introduction\b|\n\s*introduction\b|\n\s*keywords\b|\n\s*references\b)",
        r"(?is)\babstract\b\s*[:.\-]?\s*(.*?)(?:\n\s*1\s+[A-Z][^\n]{0,80}\n)",
    ]

    for pattern in patterns:
        match = re.search(pattern, raw)

        if match:
            abstract = normalize_space(match.group(1))
            abstract = re.sub(r"^[-:.\s]+", "", abstract).strip()

            if len(abstract.split()) >= 20:
                return abstract, "regex_abstract_section"

    # fallback: 如果没有 Abstract 标题，取标题和第一节之间较短的正文片段
    cleaned = normalize_space(raw)
    return "", "no_abstract_found"


def write_jsonl(rows, path):
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


# =========================
# Validate config
# =========================
if not OPENREVIEW_COOKIE.strip():
    raise ValueError("Please fill OPENREVIEW_COOKIE before running this script.")

links_df = pd.read_csv(LINKS_CSV)
print(f"Loaded links: {len(links_df)}")


# =========================
# Batch download and extract abstracts
# =========================
success_rows = []
failed_rows = []

for i, row in links_df.iterrows():
    openreview_id = str(row.get("openreview_id") or "").strip()
    pdf_url = str(row.get("openreview_pdf_url") or "").strip()

    if not openreview_id or not pdf_url:
        failed_rows.append({
            **row.to_dict(),
            "download_success": False,
            "error": "missing_openreview_id_or_pdf_url",
        })
        continue

    pdf_path = PDF_DIR / f"{row['year']}_{safe_filename(openreview_id)}.pdf"
    txt_path = TXT_DIR / f"{row['year']}_{safe_filename(openreview_id)}.txt"

    print(f"[{i + 1}/{len(links_df)}] {row['year']} {openreview_id}")

    if not pdf_path.exists() or pdf_path.stat().st_size == 0:
        result = request_pdf_with_cookie(
            url=pdf_url,
            cookie=OPENREVIEW_COOKIE,
            n_retry=N_RETRY,
        )

        if not result["success"]:
            failed_rows.append({
                **row.to_dict(),
                "download_success": False,
                "error": result["error"],
            })
            continue

        pdf_path.write_bytes(result["content"])

        time.sleep(SLEEP_SECONDS + random.uniform(0, 0.5))

    ok, err = pdf_to_text(pdf_path, txt_path)

    if not ok:
        failed_rows.append({
            **row.to_dict(),
            "download_success": True,
            "pdf_path": str(pdf_path),
            "error": f"pdftotext_failed: {err}",
        })
        continue

    text = txt_path.read_text(encoding="utf-8", errors="ignore")
    abstract, abstract_method = extract_abstract_from_text(text)

    if not abstract:
        failed_rows.append({
            **row.to_dict(),
            "download_success": True,
            "pdf_path": str(pdf_path),
            "txt_path": str(txt_path),
            "error": "abstract_not_found",
        })
        continue

    success_rows.append({
        **row.to_dict(),
        "reconstructed_abstract": abstract,
        "abstract_source": "openreview_pdf",
        "abstract_extraction_method": abstract_method,
        "pdf_path": str(pdf_path),
        "txt_path": str(txt_path),
    })


success_df = pd.DataFrame(success_rows)
failed_df = pd.DataFrame(failed_rows)

success_df.to_csv(OUT_CSV, index=False, encoding="utf-8-sig")
failed_df.to_csv(FAILED_CSV, index=False, encoding="utf-8-sig")
write_jsonl(success_rows, OUT_JSONL)

print("=" * 80)
print("ICLR Tiny Papers OpenReview PDF abstract extraction summary")
print("=" * 80)
print(f"Total links:       {len(links_df)}")
print(f"Successful:        {len(success_df)}")
print(f"Failed:            {len(failed_df)}")
print(f"Saved abstracts:   {OUT_CSV}")
print(f"Saved jsonl:       {OUT_JSONL}")
print(f"Saved failed rows: {FAILED_CSV}")

display(success_df.head())
display(failed_df.head())

Loaded links: 413
[1/413] 2023 qqKO_rrg9y
[Retry 1/4] https://openreview.net/pdf?id=qqKO_rrg9y: Non-PDF response. status=200, content_type=text/html; charset=utf-8, first_bytes=b'<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="utf-8" />\n  <meta name='; wait 2.2s
[Retry 2/4] https://openreview.net/pdf?id=qqKO_rrg9y: Non-PDF response. status=200, content_type=text/html; charset=utf-8, first_bytes=b'<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="utf-8" />\n  <meta name='; wait 3.3s
[Retry 3/4] https://openreview.net/pdf?id=qqKO_rrg9y: Non-PDF response. status=200, content_type=text/html; charset=utf-8, first_bytes=b'<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="utf-8" />\n  <meta name='; wait 5.2s
[Retry 4/4] https://openreview.net/pdf?id=qqKO_rrg9y: Non-PDF response. status=200, content_type=text/html; charset=utf-8, first_bytes=b'<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="utf-8" />\n  <meta name='; wait 6.6s

KeyboardInterrupt:

In [2]:
import json
import re
import math
from pathlib import Path
from collections import defaultdict

import pandas as pd
from tqdm import tqdm


# =========================
# Paths
# =========================
PROJECT_ROOT = Path("/home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications")

DBLP_DIR = PROJECT_ROOT / "Data/20260706_dblp"
JSONL_DIR = PROJECT_ROOT / "Data/20260712_dblp_source_enrichment"

OUT_DIR = PROJECT_ROOT / "Data/20260713_dblp_jsonl_coverage"
OUT_DIR.mkdir(parents=True, exist_ok=True)


# =========================
# Helpers
# =========================
def clean_str(x):
    if x is None:
        return ""
    if isinstance(x, float) and math.isnan(x):
        return ""
    return str(x).strip()


def normalize_doi(doi):
    doi = clean_str(doi).lower()
    doi = doi.replace("https://doi.org/", "")
    doi = doi.replace("http://doi.org/", "")
    doi = doi.replace("https://dx.doi.org/", "")
    doi = doi.replace("http://dx.doi.org/", "")
    doi = doi.replace("doi:", "")
    return doi.strip().rstrip(".")


def normalize_title(title):
    title = clean_str(title).lower()
    title = re.sub(r"[^a-z0-9]+", " ", title)
    title = re.sub(r"\s+", " ", title).strip()
    return title


def normalize_text(text):
    text = clean_str(text).lower()
    text = re.sub(r"\s+", " ", text).strip()
    return text


def get_track_name(obj):
    if not isinstance(obj, dict):
        return ""
    for key in ["track_name", "section/track_name", "section_track_name"]:
        value = clean_str(obj.get(key))
        if value:
            return value
    return ""


def get_year(value):
    try:
        if clean_str(value) == "":
            return None
        return int(float(value))
    except Exception:
        return None


def build_full_key(conference, year, title, proceedings_type, proceedings_name, track_type, track_name):
    return (
        normalize_text(conference).upper(),
        get_year(year),
        normalize_title(title),
        normalize_text(proceedings_type),
        normalize_text(proceedings_name),
        normalize_text(track_type),
        normalize_text(track_name),
    )


def build_simple_key(conference, year, title):
    return (
        normalize_text(conference).upper(),
        get_year(year),
        normalize_title(title),
    )


def add_to_index(index, key, jsonl_id):
    if not jsonl_id:
        return
    if key is None:
        return
    index[key].append(jsonl_id)


def get_jsonl_path(conference):
    conference_lower = conference.lower()
    path = JSONL_DIR / f"{conference_lower}_combined_openalex_with_abstract_dblp_enriched.jsonl"
    if path.exists():
        return path

    candidates = list(JSONL_DIR.glob(f"{conference_lower}_combined*.jsonl"))
    if candidates:
        return candidates[0]

    return None


def build_jsonl_indexes(jsonl_path, conference):
    doi_index = defaultdict(list)
    full_key_index = defaultdict(list)
    simple_key_index = defaultdict(list)

    n_jsonl = 0

    with open(jsonl_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            item = json.loads(line)
            n_jsonl += 1

            jsonl_id = clean_str(item.get("id"))

            dblp_source = item.get("dblp_source")
            if not isinstance(dblp_source, dict):
                dblp_source = {}

            item_conference = (
                dblp_source.get("conference")
                or item.get("conference")
                or conference
            )

            item_year = (
                dblp_source.get("year")
                or dblp_source.get("Year")
                or item.get("publication_year")
                or item.get("year")
                or item.get("Year")
            )

            item_title = (
                dblp_source.get("title")
                or item.get("title")
                or item.get("display_name")
            )

            item_doi = (
                dblp_source.get("doi")
                or item.get("doi")
            )

            proceedings_type = (
                dblp_source.get("proceedings_type")
                or item.get("proceedings_type")
            )

            proceedings_name = (
                dblp_source.get("proceedings_name")
                or item.get("proceedings_name")
            )

            track_type = (
                dblp_source.get("track_type")
                or item.get("track_type")
            )

            track_name = (
                get_track_name(dblp_source)
                or get_track_name(item)
            )

            doi_key = normalize_doi(item_doi)
            if doi_key:
                add_to_index(doi_index, doi_key, jsonl_id)

            full_key = build_full_key(
                item_conference,
                item_year,
                item_title,
                proceedings_type,
                proceedings_name,
                track_type,
                track_name,
            )
            add_to_index(full_key_index, full_key, jsonl_id)

            simple_key = build_simple_key(
                item_conference,
                item_year,
                item_title,
            )
            add_to_index(simple_key_index, simple_key, jsonl_id)

    return {
        "doi": doi_index,
        "full_key": full_key_index,
        "simple_key": simple_key_index,
        "n_jsonl": n_jsonl,
    }


def match_dblp_row(row, conference, indexes):
    row_doi = normalize_doi(row.get("doi"))

    if row_doi and row_doi in indexes["doi"]:
        ids = sorted(set(indexes["doi"][row_doi]))
        return True, "; ".join(ids), "doi", len(ids)

    track_name = clean_str(row.get("track_name")) or clean_str(row.get("section/track_name"))

    full_key = build_full_key(
        conference,
        row.get("year"),
        row.get("title"),
        row.get("proceedings_type"),
        row.get("proceedings_name"),
        row.get("track_type"),
        track_name,
    )

    if full_key in indexes["full_key"]:
        ids = sorted(set(indexes["full_key"][full_key]))
        return True, "; ".join(ids), "conference_year_title_proceedings_track", len(ids)

    simple_key = build_simple_key(
        conference,
        row.get("year"),
        row.get("title"),
    )

    if simple_key in indexes["simple_key"]:
        ids = sorted(set(indexes["simple_key"][simple_key]))
        return True, "; ".join(ids), "conference_year_title", len(ids)

    return False, "", "unmatched", 0


# =========================
# Main processing
# =========================
all_augmented = []
summary_rows = []

dblp_paths = sorted(DBLP_DIR.glob("*_dblp_2020_2025_all_tracks.csv"))

for dblp_path in tqdm(dblp_paths, desc="Conferences"):
    conference = dblp_path.name.split("_dblp_")[0].upper()

    jsonl_path = get_jsonl_path(conference)
    if jsonl_path is None:
        print(f"[Warning] No JSONL found for {conference}, skipped.")
        continue

    print(f"\nProcessing {conference}")
    print("DBLP:", dblp_path)
    print("JSONL:", jsonl_path)

    dblp_df = pd.read_csv(dblp_path)

    if "track_name" not in dblp_df.columns:
        if "section/track_name" in dblp_df.columns:
            dblp_df["track_name"] = dblp_df["section/track_name"]
        else:
            dblp_df["track_name"] = ""

    indexes = build_jsonl_indexes(jsonl_path, conference)

    match_results = []
    for _, row in dblp_df.iterrows():
        is_in_jsonl, jsonl_id, match_method, match_n = match_dblp_row(
            row=row,
            conference=conference,
            indexes=indexes,
        )
        match_results.append({
            "is_in_jsonl": is_in_jsonl,
            "jsonl_id": jsonl_id,
            "jsonl_match_method": match_method,
            "jsonl_match_n": match_n,
        })

    match_df = pd.DataFrame(match_results)
    augmented_df = pd.concat([dblp_df.reset_index(drop=True), match_df], axis=1)

    out_csv = OUT_DIR / f"{conference.lower()}_dblp_2020_2025_all_tracks_with_jsonl_coverage.csv"
    augmented_df.to_csv(out_csv, index=False, encoding="utf-8-sig")

    all_augmented.append(augmented_df)

    summary_rows.append({
        "conference": conference,
        "n_dblp": len(augmented_df),
        "n_jsonl": indexes["n_jsonl"],
        "n_matched": int(augmented_df["is_in_jsonl"].sum()),
        "coverage_rate_%": augmented_df["is_in_jsonl"].mean() * 100,
        "output_csv": str(out_csv),
    })


# =========================
# Save combined augmented DBLP data
# =========================
all_df = pd.concat(all_augmented, ignore_index=True)

all_out = OUT_DIR / "all_conferences_dblp_2020_2025_all_tracks_with_jsonl_coverage.csv"
all_df.to_csv(all_out, index=False, encoding="utf-8-sig")


# =========================
# Coverage by proceedings/track
# =========================
coverage_cols = [
    "conference",
    "year",
    "proceedings_type",
    "proceedings_name",
    "track_type",
    "track_name",
]

coverage_detail = (
    all_df
    .groupby(coverage_cols, dropna=False)
    .agg(
        n_dblp_papers=("title", "size"),
        n_in_jsonl=("is_in_jsonl", "sum"),
    )
    .reset_index()
)

coverage_detail["coverage_rate_%"] = (
    coverage_detail["n_in_jsonl"] / coverage_detail["n_dblp_papers"] * 100
)

coverage_detail = coverage_detail.sort_values(
    ["conference", "year", "proceedings_type", "proceedings_name", "track_type", "track_name"]
)

coverage_detail_out = OUT_DIR / "coverage_by_conference_year_proceedings_track.csv"
coverage_detail.to_csv(coverage_detail_out, index=False, encoding="utf-8-sig")


# =========================
# More compact coverage tables
# =========================
coverage_year_track = (
    all_df
    .groupby(["conference", "year", "proceedings_type", "track_type"], dropna=False)
    .agg(
        n_dblp_papers=("title", "size"),
        n_in_jsonl=("is_in_jsonl", "sum"),
    )
    .reset_index()
)

coverage_year_track["coverage_rate_%"] = (
    coverage_year_track["n_in_jsonl"] / coverage_year_track["n_dblp_papers"] * 100
)

coverage_year_track_out = OUT_DIR / "coverage_by_conference_year_track_type.csv"
coverage_year_track.to_csv(coverage_year_track_out, index=False, encoding="utf-8-sig")


conference_summary = pd.DataFrame(summary_rows).sort_values("conference")
conference_summary_out = OUT_DIR / "coverage_by_conference_summary.csv"
conference_summary.to_csv(conference_summary_out, index=False, encoding="utf-8-sig")


print("\nSaved outputs:")
print("All augmented DBLP:", all_out)
print("Detailed coverage:", coverage_detail_out)
print("Year-track coverage:", coverage_year_track_out)
print("Conference summary:", conference_summary_out)

display(conference_summary)
display(coverage_year_track.head(30))

Conferences:   0%|          | 0/10 [00:00<?, ?it/s]

Processing AAAI
DBLP: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260706_dblp/aaai_dblp_2020_2025_all_tracks.csv
JSONL: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260712_dblp_source_enrichment/aaai_combined_openalex_with_abstract_dblp_enriched.jsonl

Conferences:  10%|█         | 1/10 [00:04<00:37,  4.14s/it]

Processing ACL
DBLP: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260706_dblp/acl_dblp_2020_2025_all_tracks.csv
JSONL: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260712_dblp_source_enrichment/acl_combined_openalex_with_abstract_dblp_enriched.jsonl

Conferences:  20%|██        | 2/10 [00:06<00:23,  2.99s/it]

Processing CVPR
DBLP: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260706_dblp/cvpr_dblp_2020_2025_all_tracks.csv
JSONL: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260712_dblp_source_enrichment/cvpr_combined_openalex_with_abstract_dblp_enriched.jsonl

Conferences:  30%|███       | 3/10 [00:10<00:24,  3.50s/it]

Processing EMNLP
DBLP: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260706_dblp/emnlp_dblp_2020_2025_all_tracks.csv
JSONL: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260712_dblp_source_enrichment/emnlp_combined_openalex_with_abstract_dblp_enriched.jsonl

Conferences:  40%|████      | 4/10 [00:13<00:19,  3.17s/it]

Processing ICLR
DBLP: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260706_dblp/iclr_dblp_2020_2025_all_tracks.csv
JSONL: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260712_dblp_source_enrichment/iclr_combined_openalex_with_abstract_dblp_enriched.jsonl

Conferences:  50%|█████     | 5/10 [00:15<00:13,  2.74s/it]

Processing ICML
DBLP: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260706_dblp/icml_dblp_2020_2025_all_tracks.csv
JSONL: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260712_dblp_source_enrichment/icml_combined_openalex_with_abstract_dblp_enriched.jsonl

Conferences:  60%|██████    | 6/10 [00:17<00:10,  2.52s/it]

Processing IJCAI
DBLP: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260706_dblp/ijcai_dblp_2020_2025_all_tracks.csv
JSONL: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260712_dblp_source_enrichment/ijcai_combined_openalex_with_abstract_dblp_enriched.jsonl

Conferences:  70%|███████   | 7/10 [00:18<00:06,  2.11s/it]

Processing KDD
DBLP: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260706_dblp/kdd_dblp_2020_2025_all_tracks.csv
JSONL: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260712_dblp_source_enrichment/kdd_combined_openalex_with_abstract_dblp_enriched.jsonl

Conferences:  80%|████████  | 8/10 [00:19<00:03,  1.62s/it]

Processing SIGIR
DBLP: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260706_dblp/sigir_dblp_2020_2025_all_tracks.csv
JSONL: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260712_dblp_source_enrichment/sigir_combined_openalex_with_abstract_dblp_enriched.jsonl

Conferences:  90%|█████████ | 9/10 [00:19<00:01,  1.25s/it]

Processing WWW
DBLP: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260706_dblp/www_dblp_2020_2025_all_tracks.csv
JSONL: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260712_dblp_source_enrichment/www_combined_openalex_with_abstract_dblp_enriched.jsonl

Conferences: 100%|██████████| 10/10 [00:20<00:00,  2.02s/it]

Saved outputs:
All augmented DBLP: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260713_dblp_jsonl_coverage/all_conferences_dblp_2020_2025_all_tracks_with_jsonl_coverage.csv
Detailed coverage: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260713_dblp_jsonl_coverage/coverage_by_conference_year_proceedings_track.csv
Year-track coverage: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260713_dblp_jsonl_coverage/coverage_by_conference_year_track_type.csv
Conference summary: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260713_dblp_jsonl_coverage/coverage_by_conference_summary.csv

,conference,n_dblp,n_jsonl,n_matched,coverage_rate_%,output_csv
0,AAAI,14116,13840,13840,98.044772,/home/user/GSK/lily/science_of_science/NewData...
1,ACL,10740,10714,10714,99.757914,/home/user/GSK/lily/science_of_science/NewData...
2,CVPR,16922,16834,16841,99.521333,/home/user/GSK/lily/science_of_science/NewData...
3,EMNLP,12303,12284,12284,99.845566,/home/user/GSK/lily/science_of_science/NewData...
4,ICLR,10591,10537,10505,99.187990,/home/user/GSK/lily/science_of_science/NewData...
5,ICML,11313,11318,11295,99.840891,/home/user/GSK/lily/science_of_science/NewData...
6,IJCAI,5698,5553,5552,97.437697,/home/user/GSK/lily/science_of_science/NewData...
7,KDD,3507,3409,3409,97.205589,/home/user/GSK/lily/science_of_science/NewData...
8,SIGIR,2636,2575,2575,97.685888,/home/user/GSK/lily/science_of_science/NewData...
9,WWW,4064,3998,3998,98.375984,/home/user/GSK/lily/science_of_science/NewData...

,conference,year,proceedings_type,track_type,n_dblp_papers,n_in_jsonl,coverage_rate_%
0,AAAI,2020,main_proceedings,main_track,1584,1583,99.936869
1,AAAI,2020,main_proceedings,non-main_track,280,279,99.642857
2,AAAI,2020,non-main_proceedings,non-main_track,41,0,0.000000
3,AAAI,2021,main_proceedings,main_track,1654,1654,100.000000
4,AAAI,2021,main_proceedings,non-main_track,307,306,99.674267
5,AAAI,2021,non-main_proceedings,non-main_track,102,3,2.941176
6,AAAI,2022,main_proceedings,main_track,1319,1319,100.000000
7,AAAI,2022,main_proceedings,non-main_track,305,304,99.672131
8,AAAI,2022,non-main_proceedings,non-main_track,56,5,8.928571
9,AAAI,2023,main_proceedings,main_track,1578,1578,100.000000
10,AAAI,2023,main_proceedings,non-main_track,443,442,99.774266
11,AAAI,2023,non-main_proceedings,non-main_track,56,11,19.642857
12,AAAI,2024,main_proceedings,main_track,2500,2500,100.000000
13,AAAI,2024,main_proceedings,non-main_track,365,365,100.000000
14,AAAI,2024,non-main_proceedings,non-main_track,17,1,5.882353
15,AAAI,2025,main_proceedings,main_track,3028,3028,100.000000
16,AAAI,2025,main_proceedings,non-main_track,458,457,99.781659
17,AAAI,2025,non-main_proceedings,non-main_track,23,5,21.739130
18,ACL,2020,main_proceedings,main_track,778,778,100.000000
19,ACL,2020,non-main_proceedings,non-main_track,109,108,99.082569
20,ACL,2021,main_proceedings,main_track,710,710,100.000000
21,ACL,2021,non-main_proceedings,non-main_track,536,530,98.880597
22,ACL,2022,main_proceedings,main_track,700,700,100.000000
23,ACL,2022,non-main_proceedings,non-main_track,405,403,99.506173
24,ACL,2023,main_proceedings,main_track,1074,1074,100.000000
25,ACL,2023,non-main_proceedings,non-main_track,1074,1073,99.906890
26,ACL,2024,main_proceedings,main_track,932,932,100.000000
27,ACL,2024,non-main_proceedings,non-main_track,1069,1053,98.503274
28,ACL,2025,main_proceedings,main_track,1699,1699,100.000000
29,ACL,2025,non-main_proceedings,non-main_track,1654,1654,100.000000

In [ ]:

from pathlib import Path


import pandas as pd


# =========================
# Paths
# =========================
PROJECT_ROOT = Path("/home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications")

COVERAGE_DIR = PROJECT_ROOT / "Data/202607013_dblp_jsonl_coverage"

OUT_DIR = PROJECT_ROOT / "Data/20260713_dblp_not_in_jsonl"
OUT_DIR.mkdir(parents=True, exist_ok=True)

paths = sorted(COVERAGE_DIR.glob("*_dblp_2020_2025_all_tracks_with_jsonl_coverage.csv"))

for path in paths:
    df = pd.read_csv("path")
    not_df = df[df['is_in_jsonl'] == False]
    conference = path.name.split("_dblp_")[0].upper()
    print(not_df.head())
    not_df.to_csv(OUT_DIR / f"{conference}_not_in_jsonl.csv")

In [7]:
from pathlib import Path
import pandas as pd


# =========================
# Paths
# =========================
PROJECT_ROOT = Path("/home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications")

COVERAGE_DIR = PROJECT_ROOT / "Data/20260713_dblp_jsonl_coverage"
OUT_DIR = PROJECT_ROOT / "Data/20260713_dblp_not_in_jsonl"
OUT_DIR.mkdir(parents=True, exist_ok=True)


paths = sorted(COVERAGE_DIR.glob("*_dblp_2020_2025_all_tracks_with_jsonl_coverage.csv"))

print(f"Found {len(paths)} coverage files.")

for path in paths:
    df = pd.read_csv(path)

    if df["is_in_jsonl"].dtype == bool:
        not_df = df[df["is_in_jsonl"] == False].copy()
    else:
        not_df = df[df["is_in_jsonl"].astype(str).str.lower() == "false"].copy()

    conference = path.name.split("_dblp_")[0].upper()

    print(f"{conference}: not in jsonl = {len(not_df)}")
    print(not_df.head())

    not_df.to_csv(
        OUT_DIR / f"{conference.lower()}_not_in_jsonl.csv",
        index=False,
        encoding="utf-8-sig"
    )

Found 11 coverage files.
AAAI: not in jsonl = 276
     conference  year                                              title  \
1232       AAAI  2020  An Efficient Algorithm for Counting Markov Equ...
1663       AAAI  2020                          Model AI Assignments 2020
1864       AAAI  2020  A Deep Learning Approach Towards Multimodal St...
1865       AAAI  2020  A Siamese Neural Network with Modified Distanc...
1866       AAAI  2020  Attentive RNNs for Continuous-time Emotion Pre...

                                                authors  \
1232          Robert Ganian; Thekla Hamm; Topi Talvitie
1663  Todd W. Neller; Stephen Keeley; Michael Guerzh...
1864  Cristian-Paul Bara; Michalis Papakostas; Rada ...
1865                      Kexin Feng; Theodora Chaspari
1866  Sanga Chaki; Pranjal Doshi; Priyadarshi Patnai...

                           doi                                     source_url  \
1232                       NaN    https://dblp.org/db/conf/aaai/aaai2020.html
1663  10.1609/aaai.v34i09.7072    https://dblp.org/db/conf/aaai/aaai2020.html
1864                       NaN  https://dblp.org/db/conf/aaai/affcon2020.html
1865                       NaN  https://dblp.org/db/conf/aaai/affcon2020.html
1866                       NaN  https://dblp.org/db/conf/aaai/affcon2020.html

          proceedings_type  proceedings_name      track_type  \
1232      main_proceedings               NaN      main_track
1663      main_proceedings               NaN  non-main_track
1864  non-main_proceedings               NaN  non-main_track
1865  non-main_proceedings               NaN  non-main_track
1866  non-main_proceedings               NaN  non-main_track

                                     section/track_name  \
1232  AAAI Technical Track: Reasoning under Uncertainty
1663               EAAI Symposium: Model AI Assignments
1864                                 AffCon20_session 1
1865                                 AffCon20_session 1
1866                                 AffCon20_session 1

                                             track_name  is_in_jsonl jsonl_id  \
1232  AAAI Technical Track: Reasoning under Uncertainty        False      NaN
1663               EAAI Symposium: Model AI Assignments        False      NaN
1864                                 AffCon20_session 1        False      NaN
1865                                 AffCon20_session 1        False      NaN
1866                                 AffCon20_session 1        False      NaN

     jsonl_match_method  jsonl_match_n
1232          unmatched              0
1663          unmatched              0
1864          unmatched              0
1865          unmatched              0
1866          unmatched              0
ACL: not in jsonl = 26
     conference  year                                              title  \
858         ACL  2020  Usnea: An Authorship Tool for Interactive Fict...
1660        ACL  2021  Beyond Metadata: What Paper Authors Say About ...
1733        ACL  2021  Dynamic and Multi-Channel Graph Convolutional ...
1913        ACL  2021  Named Entity Recognition via Noise Aware Train...
1949        ACL  2021  Prediction or Comparison: Toward Interpretable...

                                                authors  \
858                             Ben Swanson; Boris Smus
1660      Nikolay Kolyada; Martin Potthast; Benno Stein
1733  Shiguan Pang; Yun Xue; Zehao Yan; Weihao Huang...
1913  Xiusheng Huang; Yubo Chen; Shun Wu; Jun Zhao; ...
1949                 Mucheng Ren; Heyan Huang; Yang Gao

                                    doi  \
858       10.18653/v1/2020.acl-demos.29
1660  10.18653/v1/2021.findings-acl.451
1733  10.18653/v1/2021.findings-acl.232
1913  10.18653/v1/2021.findings-acl.423
1949   10.18653/v1/2021.findings-acl.59

                                       source_url      proceedings_type  \
858   https://dblp.org/db/conf/acl/acl2020-d.html  non-main_proceedings
1660   https://dblp.org/db/conf/acl/acl2021f.html  non-main_proceedings
1733   https://dblp.org/db/conf/acl/acl2021f.html  non-main_proceedings
1913   https://dblp.org/db/conf/acl/acl2021f.html  non-main_proceedings
1949   https://dblp.org/db/conf/acl/acl2021f.html  non-main_proceedings

                                       proceedings_name      track_type  \
858   Proceedings of the 58th Annual Meeting of the ...  non-main_track
1660  Findings of the Association for Computational ...  non-main_track
1733  Findings of the Association for Computational ...  non-main_track
1913  Findings of the Association for Computational ...  non-main_track
1949  Findings of the Association for Computational ...  non-main_track

                                     section/track_name  \
858   Proceedings of the 58th Annual Meeting of the ...
1660  Findings of the Association for Computational ...
1733  Findings of the Association for Computational ...
1913  Findings of the Association for Computational ...
1949  Findings of the Association for Computational ...

                                             track_name  is_in_jsonl jsonl_id  \
858   Proceedings of the 58th Annual Meeting of the ...        False      NaN
1660  Findings of the Association for Computational ...        False      NaN
1733  Findings of the Association for Computational ...        False      NaN
1913  Findings of the Association for Computational ...        False      NaN
1949  Findings of the Association for Computational ...        False      NaN

     jsonl_match_method  jsonl_match_n
858           unmatched              0
1660          unmatched              0
1733          unmatched              0
1913          unmatched              0
1949          unmatched              0

/tmp/ipykernel_3154037/1579495044.py:20: DtypeWarning: Columns (15,16,17,19,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

ALL_CONFERENCES: not in jsonl = 877
     conference  year                                              title  \
1232       AAAI  2020  An Efficient Algorithm for Counting Markov Equ...
1663       AAAI  2020                          Model AI Assignments 2020
1864       AAAI  2020  A Deep Learning Approach Towards Multimodal St...
1865       AAAI  2020  A Siamese Neural Network with Modified Distanc...
1866       AAAI  2020  Attentive RNNs for Continuous-time Emotion Pre...

                                                authors  \
1232          Robert Ganian; Thekla Hamm; Topi Talvitie
1663  Todd W. Neller; Stephen Keeley; Michael Guerzh...
1864  Cristian-Paul Bara; Michalis Papakostas; Rada ...
1865                      Kexin Feng; Theodora Chaspari
1866  Sanga Chaki; Pranjal Doshi; Priyadarshi Patnai...

                           doi                                     source_url  \
1232                       NaN    https://dblp.org/db/conf/aaai/aaai2020.html
1663  10.1609/aaai.v34i09.7072    https://dblp.org/db/conf/aaai/aaai2020.html
1864                       NaN  https://dblp.org/db/conf/aaai/affcon2020.html
1865                       NaN  https://dblp.org/db/conf/aaai/affcon2020.html
1866                       NaN  https://dblp.org/db/conf/aaai/affcon2020.html

          proceedings_type proceedings_name      track_type  \
1232      main_proceedings              NaN      main_track
1663      main_proceedings              NaN  non-main_track
1864  non-main_proceedings              NaN  non-main_track
1865  non-main_proceedings              NaN  non-main_track
1866  non-main_proceedings              NaN  non-main_track

                                     section/track_name  ...  \
1232  AAAI Technical Track: Reasoning under Uncertainty  ...
1663               EAAI Symposium: Model AI Assignments  ...
1864                                 AffCon20_session 1  ...
1865                                 AffCon20_session 1  ...
1866                                 AffCon20_session 1  ...

     jsonl_match_method  jsonl_match_n doi_norm_before title_norm  \
1232          unmatched              0             NaN        NaN
1663          unmatched              0             NaN        NaN
1864          unmatched              0             NaN        NaN
1865          unmatched              0             NaN        NaN
1866          unmatched              0             NaN        NaN

      doi_supplement_source ijcai_2024_paper_number ijcai_2024_paper_url  \
1232                    NaN                     NaN                  NaN
1663                    NaN                     NaN                  NaN
1864                    NaN                     NaN                  NaN
1865                    NaN                     NaN                  NaN
1866                    NaN                     NaN                  NaN

     ijcai_2024_official_title  doi_match_method doi_match_score
1232                       NaN               NaN             NaN
1663                       NaN               NaN             NaN
1864                       NaN               NaN             NaN
1865                       NaN               NaN             NaN
1866                       NaN               NaN             NaN

[5 rows x 23 columns]
CVPR: not in jsonl = 81
     conference  year                                              title  \
1602       CVPR  2020  Detection and Retrieval of Out-of-Distribution...
1711       CVPR  2020  Intelligent Scene Caching to Improve Accuracy ...
1803       CVPR  2020      On indirect assessment of heart rate in video
1841       CVPR  2020  Reducing catastrophic forgetting with learning...
1897       CVPR  2020  SomethingFinder: Localizing undefined regions ...

                                                authors  \
1602  Philipp Oberdiek; Matthias Rottmann; Gernot A....
1711  Benjamin Simpson; Ekdeep Singh Lubana; Yuchen ...
1803  Mikhail Kopeliovich; Konstantin Kalinin; Yuriy...
1841                 Wojciech Masarczyk; Ivona Tautkute
1897           Sungmin Eum; David K. Han; Gordon Briggs

                                doi  \
1602  10.1109/cvprw50498.2020.00172
1711  10.1109/cvprw50498.2020.00370
1803  10.1109/cvprw50498.2020.00163
1841  10.1109/cvprw50498.2020.00134
1897  10.1109/cvprw50498.2020.00198

                                        source_url      proceedings_type  \
1602  https://dblp.org/db/conf/cvpr/cvprw2020.html  non-main_proceedings
1711  https://dblp.org/db/conf/cvpr/cvprw2020.html  non-main_proceedings
1803  https://dblp.org/db/conf/cvpr/cvprw2020.html  non-main_proceedings
1841  https://dblp.org/db/conf/cvpr/cvprw2020.html  non-main_proceedings
1897  https://dblp.org/db/conf/cvpr/cvprw2020.html  non-main_proceedings

                                       proceedings_name      track_type  \
1602  2020 IEEE/CVF Conference on Computer Vision an...  non-main_track
1711  2020 IEEE/CVF Conference on Computer Vision an...  non-main_track
1803  2020 IEEE/CVF Conference on Computer Vision an...  non-main_track
1841  2020 IEEE/CVF Conference on Computer Vision an...  non-main_track
1897  2020 IEEE/CVF Conference on Computer Vision an...  non-main_track

                                     section/track_name  \
1602  2020 IEEE/CVF Conference on Computer Vision an...
1711  2020 IEEE/CVF Conference on Computer Vision an...
1803  2020 IEEE/CVF Conference on Computer Vision an...
1841  2020 IEEE/CVF Conference on Computer Vision an...
1897  2020 IEEE/CVF Conference on Computer Vision an...

                                             track_name  is_in_jsonl jsonl_id  \
1602  2020 IEEE/CVF Conference on Computer Vision an...        False      NaN
1711  2020 IEEE/CVF Conference on Computer Vision an...        False      NaN
1803  2020 IEEE/CVF Conference on Computer Vision an...        False      NaN
1841  2020 IEEE/CVF Conference on Computer Vision an...        False      NaN
1897  2020 IEEE/CVF Conference on Computer Vision an...        False      NaN

     jsonl_match_method  jsonl_match_n
1602          unmatched              0
1711          unmatched              0
1803          unmatched              0
1841          unmatched              0
1897          unmatched              0
EMNLP: not in jsonl = 19
     conference  year                                              title  \
284       EMNLP  2020  H2KGAT: Hierarchical Hyperbolic Knowledge Grap...
991       EMNLP  2020  Language-Conditioned Feature Pyramids for Visu...
1234      EMNLP  2020  Vapur: A Search Engine to Find Related Protein...
6447      EMNLP  2024  AmbigNLG: Addressing Task Ambiguity in Instruc...
6476      EMNLP  2024  Are Large Language Models In-Context Personali...

                                                authors  \
284   Shen Wang; Xiaokai Wei; Cícero Nogueira dos Sa...
991                            Taichi Iki; Akiko Aizawa
1234  Abdullatif Köksal; Hilal Dönmez; Riza Özçelik;...
6447                             Ayana Niwa; Hayate Iso
6476  Divya Patel; Pathik Patel; Ankush Chander; Sou...

                                      doi  \
284                                   NaN
991   10.18653/v1/2020.findings-emnlp.420
1234     10.18653/v1/2020.nlpcovid19-2.21
6447      10.18653/v1/2024.emnlp-main.599
6476      10.18653/v1/2024.emnlp-main.935

                                           source_url      proceedings_type  \
284   https://dblp.org/db/conf/emnlp/emnlp2020-1.html      main_proceedings
991    https://dblp.org/db/conf/emnlp/emnlp2020f.html  non-main_proceedings
1234    https://dblp.org/db/conf/emnlp/covid2020.html  non-main_proceedings
6447    https://dblp.org/db/conf/emnlp/emnlp2024.html      main_proceedings
6476    https://dblp.org/db/conf/emnlp/emnlp2024.html      main_proceedings

                                       proceedings_name      track_type  \
284   Proceedings of the 2020 Conference on Empirica...      main_track
991   Findings of the Association for Computational ...  non-main_track
1234  Proceedings of the 1st Workshop on NLP for COV...  non-main_track
6447  Proceedings of the 2024 Conference on Empirica...      main_track
6476  Proceedings of the 2024 Conference on Empirica...      main_track

                                     section/track_name  \
284   Proceedings of the 2020 Conference on Empirica...
991   Findings of the Association for Computational ...
1234  Proceedings of the 1st Workshop on NLP for COV...
6447  Proceedings of the 2024 Conference on Empirica...
6476  Proceedings of the 2024 Conference on Empirica...

                                             track_name  is_in_jsonl jsonl_id  \
284   Proceedings of the 2020 Conference on Empirica...        False      NaN
991   Findings of the Association for Computational ...        False      NaN
1234  Proceedings of the 1st Workshop on NLP for COV...        False      NaN
6447  Proceedings of the 2024 Conference on Empirica...        False      NaN
6476  Proceedings of the 2024 Conference on Empirica...        False      NaN

     jsonl_match_method  jsonl_match_n
284           unmatched              0
991           unmatched              0
1234          unmatched              0
6447          unmatched              0
6476          unmatched              0
ICLR: not in jsonl = 86
     conference  year                                              title  \
421        ICLR  2020                              Network Deconvolution
1224       ICLR  2021               Nearest Neighbor Machine Translation
1238       ICLR  2021             Neural Spatio-Temporal Point Processes
1656       ICLR  2022                         Bootstrapped Meta-Learning
1847       ICLR  2022  Equivariant Transformers for Neural Network ba...

                                                authors  doi  \
421   Chengxi Ye; Matthew Evanusa; Hua He; Anton Mit...  NaN
1224  Urvashi Khandelwal; Angela Fan; Dan Jurafsky; ...  NaN
1238  Ricky T. Q. Chen; Brandon Amos; Maximilian Nickel  NaN
1656  Sebastian Flennerhag; Yannick Schroecker; Tom ...  NaN
1847                Philipp Thölke; Gianni De Fabritiis  NaN

                                       source_url  proceedings_type  \
421   https://dblp.org/db/conf/iclr/iclr2020.html  main_proceedings
1224  https://dblp.org/db/conf/iclr/iclr2021.html  main_proceedings
1238  https://dblp.org/db/conf/iclr/iclr2021.html  main_proceedings
1656  https://dblp.org/db/conf/iclr/iclr2022.html  main_proceedings
1847  https://dblp.org/db/conf/iclr/iclr2022.html  main_proceedings

                                       proceedings_name  track_type  \
421   8th International Conference on Learning Repre...  main_track
1224  9th International Conference on Learning Repre...  main_track
1238  9th International Conference on Learning Repre...  main_track
1656  The Tenth International Conference on Learning...  main_track
1847  The Tenth International Conference on Learning...  main_track

                                     section/track_name  \
421   8th International Conference on Learning Repre...
1224  9th International Conference on Learning Repre...
1238  9th International Conference on Learning Repre...
1656  The Tenth International Conference on Learning...
1847  The Tenth International Conference on Learning...

                                             track_name  is_in_jsonl jsonl_id  \
421   8th International Conference on Learning Repre...        False      NaN
1224  9th International Conference on Learning Repre...        False      NaN
1238  9th International Conference on Learning Repre...        False      NaN
1656  The Tenth International Conference on Learning...        False      NaN
1847  The Tenth International Conference on Learning...        False      NaN

     jsonl_match_method  jsonl_match_n
421           unmatched              0
1224          unmatched              0
1238          unmatched              0
1656          unmatched              0
1847          unmatched              0
ICML: not in jsonl = 18
     conference  year                                              title  \
756        ICML  2020  PoKED: A Semi-Supervised System for Word Sense...
1042       ICML  2020  Universal Asymptotic Optimality of Polyak Mome...
1376       ICML  2021  Defense against backdoor attacks via robust co...
2387       ICML  2022  Adversarially trained neural representations a...
3285       ICML  2022  SSL Enables Learning from Sparse Rewards in Im...

                                                authors  doi  \
756                                            Feng Wei  NaN
1042                    Damien Scieur; Fabian Pedregosa  NaN
1376  Jonathan Hayase; Weihao Kong; Raghav Somani; S...  NaN
2387  Chong Guo; Michael J. Lee; Guillaume Leclerc; ...  NaN
3285  Arjun Majumdar; Gunnar A. Sigurdsson; Robinson...  NaN

                                       source_url  proceedings_type  \
756   https://dblp.org/db/conf/icml/icml2020.html  main_proceedings
1042  https://dblp.org/db/conf/icml/icml2020.html  main_proceedings
1376  https://dblp.org/db/conf/icml/icml2021.html  main_proceedings
2387  https://dblp.org/db/conf/icml/icml2022.html  main_proceedings
3285  https://dblp.org/db/conf/icml/icml2022.html  main_proceedings

                                       proceedings_name  track_type  \
756   Proceedings of the 37th International Conferen...  main_track
1042  Proceedings of the 37th International Conferen...  main_track
1376  Proceedings of the 38th International Conferen...  main_track
2387  International Conference on Machine Learning, ...  main_track
3285  International Conference on Machine Learning, ...  main_track

                                     section/track_name  \
756   Proceedings of the 37th International Conferen...
1042  Proceedings of the 37th International Conferen...
1376  Proceedings of the 38th International Conferen...
2387  International Conference on Machine Learning, ...
3285  International Conference on Machine Learning, ...

                                             track_name  is_in_jsonl jsonl_id  \
756   Proceedings of the 37th International Conferen...        False      NaN
1042  Proceedings of the 37th International Conferen...        False      NaN
1376  Proceedings of the 38th International Conferen...        False      NaN
2387  International Conference on Machine Learning, ...        False      NaN
3285  International Conference on Machine Learning, ...        False      NaN

     jsonl_match_method  jsonl_match_n
756           unmatched              0
1042          unmatched              0
1376          unmatched              0
2387          unmatched              0
3285          unmatched              0
IJCAI: not in jsonl = 146
    conference  year                                              title  \
343      IJCAI  2020   Maximum Nash Welfare and Other Stories About EFX
778      IJCAI  2020               Comixify: turning videos into comics
779      IJCAI  2020  The Ants Have Megaphones Now: Text Mining and ...
780      IJCAI  2020  A Conceptual Framework of Intelligent Manageme...
781      IJCAI  2020  A Review of Transfer Learning for EEG-Based Dr...

                                               authors  \
343  Georgios Amanatidis; Georgios Birmpas; Aris Fi...
778                                   Tomasz Trzcinski
779                                    Georgiana Ifrim
780  Helena Dudycz; Marcin Hernes; Zdzislaw Kes; Eu...
781      Jin Cui; Yong Peng; Kenji Ozawa; Wanzeng Kong

                              doi  \
343         10.24963/ijcai.2020/4
778                           NaN
779                           NaN
780   10.1007/978-3-030-80847-1_3
781  10.1007/978-981-16-1288-6_11

                                            source_url      proceedings_type  \
343      https://dblp.org/db/conf/ijcai/ijcai2020.html      main_proceedings
778  https://dblp.org/db/conf/ijcai/ai4narratives20...  non-main_proceedings
779  https://dblp.org/db/conf/ijcai/ai4narratives20...  non-main_proceedings
780      https://dblp.org/db/conf/ijcai/ai4km2020.html  non-main_proceedings
781       https://dblp.org/db/conf/ijcai/hbai2020.html  non-main_proceedings

                                      proceedings_name      track_type  \
343  Proceedings of the Twenty-Ninth International ...      main_track
778  Proceedings of AI4Narratives - Workshop on Art...  non-main_track
779  Proceedings of AI4Narratives - Workshop on Art...  non-main_track
780  Artificial Intelligence for Knowledge Manageme...  non-main_track
781  Human Brain and Artificial Intelligence - Seco...  non-main_track

    section/track_name  ... ijcai_2024_paper_number ijcai_2024_paper_url  \
343         Main track  ...                     NaN                  NaN
778   Keynote Speakers  ...                     NaN                  NaN
779   Keynote Speakers  ...                     NaN                  NaN
780        Refine list  ...                     NaN                  NaN
781        Refine list  ...                     NaN                  NaN

    ijcai_2024_official_title  doi_match_method doi_match_score  \
343                       NaN               NaN             NaN
778                       NaN               NaN             NaN
779                       NaN               NaN             NaN
780                       NaN               NaN             NaN
781                       NaN               NaN             NaN

           track_name is_in_jsonl  jsonl_id jsonl_match_method  jsonl_match_n
343        Main track       False       NaN          unmatched              0
778  Keynote Speakers       False       NaN          unmatched              0
779  Keynote Speakers       False       NaN          unmatched              0
780       Refine list       False       NaN          unmatched              0
781       Refine list       False       NaN          unmatched              0

[5 rows x 23 columns]
KDD: not in jsonl = 98
    conference  year                                              title  \
424        KDD  2020  Attention Realignment and Pseudo-Labelling for...
427        KDD  2020                     Cost Aware Feature Elicitation
429        KDD  2020  IQ-Net: A DNN Model for Estimating Interaction...
430        KDD  2020  Improved Question Answering using Domain Predi...
431        KDD  2020  Improving Task-Oriented Dialogue Systems In Pr...

                                               authors  doi  \
424    Jitin Krishnan; Hemant Purohit; Huzefa Rangwala  NaN
427    Srijita Das; Rishabh K. Iyer; Sriraam Natarajan  NaN
429  Yuan Ling; Benjamin Z. Yao; Guneet Singh Kohli...  NaN
430  Himani Srivastava; Prerna Khurana; Saurabh Sri...  NaN
431  Alon Jacovi; Ori Bar El; Ofer Lavi; David Boaz...  NaN

                                         source_url      proceedings_type  \
424      https://dblp.org/db/conf/kdd/kiml2020.html  non-main_proceedings
427      https://dblp.org/db/conf/kdd/kiml2020.html  non-main_proceedings
429  https://dblp.org/db/conf/kdd/converse2020.html  non-main_proceedings
430  https://dblp.org/db/conf/kdd/converse2020.html  non-main_proceedings
431  https://dblp.org/db/conf/kdd/converse2020.html  non-main_proceedings

                                      proceedings_name      track_type  \
424  Proceedings of the ACM SIGKDD Workshop on Know...  non-main_track
427  Proceedings of the ACM SIGKDD Workshop on Know...  non-main_track
429  Proceedings of the KDD 2020 Workshop on Conver...  non-main_track
430  Proceedings of the KDD 2020 Workshop on Conver...  non-main_track
431  Proceedings of the KDD 2020 Workshop on Conver...  non-main_track

    section/track_name   track_name  is_in_jsonl jsonl_id jsonl_match_method  \
424        Refine list  Refine list        False      NaN          unmatched
427        Refine list  Refine list        False      NaN          unmatched
429        Refine list  Refine list        False      NaN          unmatched
430        Refine list  Refine list        False      NaN          unmatched

In [ ]:
import os
import re
import json
import time
import shutil
import random
import threading
import unicodedata
from copy import deepcopy
from pathlib import Path
from datetime import datetime
from urllib.parse import quote
from concurrent.futures import ThreadPoolExecutor, as_completed
from difflib import SequenceMatcher

import requests
import pandas as pd
from tqdm.auto import tqdm


# =========================================================
# Configuration
# =========================================================
PROJECT_ROOT = Path(
    "/home/user/GSK/lily/science_of_science/NewDataset/"
    "AI_impact_on_cs_publications"
)

JSONL_DIR = PROJECT_ROOT / "Data/20260712_dblp_source_enrichment"

CACHE_PATH = JSONL_DIR / "openalex_non_openalex_id_refetch_cache.json"
REPORT_PATH = JSONL_DIR / "openalex_non_openalex_id_refetch_report.csv"
UNMATCHED_PATH = JSONL_DIR / "openalex_non_openalex_id_unmatched.csv"

OPENALEX_API = "https://api.openalex.org/works"

# 建议填写自己的邮箱，以使用 OpenAlex polite pool
OPENALEX_MAILTO = ""

# 如果有 OpenAlex API key，可以填写；没有则留空
OPENALEX_API_KEY = ""

MAX_WORKERS = 4
MAX_RETRIES = 5
REQUEST_TIMEOUT = 45
TITLE_MATCH_THRESHOLD = 0.98

TARGET_FILES = sorted(
    JSONL_DIR.glob("*_combined_openalex_with_abstract_dblp_enriched.jsonl")
)

if not TARGET_FILES:
    raise FileNotFoundError(
        f"No combine JSONL files found in {JSONL_DIR}"
    )


# =========================================================
# Text normalization
# =========================================================
def normalize_doi(doi):
    if doi is None:
        return ""

    doi = str(doi).strip().lower()
    doi = re.sub(r"^doi:\s*", "", doi)

    prefixes = [
        "https://doi.org/",
        "http://doi.org/",
        "https://dx.doi.org/",
        "http://dx.doi.org/",
    ]

    for prefix in prefixes:
        if doi.startswith(prefix):
            doi = doi[len(prefix):]

    doi = doi.strip()
    doi = doi.rstrip(".,;:)]}")
    return doi


def normalize_title(title):
    if title is None:
        return ""

    text = str(title).strip().lower()
    text = unicodedata.normalize("NFKD", text)
    text = "".join(
        char for char in text
        if not unicodedata.combining(char)
    )

    text = re.sub(r"[^a-z0-9]+", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def is_openalex_id(value):
    return (
        isinstance(value, str)
        and value.startswith("https://openalex.org/W")
    )


def get_dblp_source(item):
    dblp_source = item.get("dblp_source")
    return dblp_source if isinstance(dblp_source, dict) else {}


def get_item_doi(item):
    dblp_source = get_dblp_source(item)

    candidates = [
        item.get("doi"),
        item.get("DOI"),
        dblp_source.get("doi"),
        dblp_source.get("DOI"),
    ]

    for value in candidates:
        doi = normalize_doi(value)
        if doi:
            return doi

    return ""


def get_item_title(item):
    dblp_source = get_dblp_source(item)

    candidates = [
        item.get("title"),
        item.get("display_name"),
        dblp_source.get("title"),
    ]

    for value in candidates:
        if value is not None and str(value).strip():
            return str(value).strip()

    return ""


def get_item_year(item):
    dblp_source = get_dblp_source(item)

    for key in ["year", "Year", "publication_year"]:
        value = item.get(key)
        if value is not None:
            try:
                return int(value)
            except Exception:
                pass

    for key in ["year", "Year", "publication_year"]:
        value = dblp_source.get(key)
        if value is not None:
            try:
                return int(value)
            except Exception:
                pass

    return None


# =========================================================
# Cache
# =========================================================
def load_cache(path):
    if not path.exists():
        return {}

    try:
        with open(path, "r", encoding="utf-8") as f:
            cache = json.load(f)

        if isinstance(cache, dict):
            return cache

    except Exception as exc:
        print(f"[Warning] Failed to load cache: {exc}")

    return {}


def save_cache(cache, path):
    temp_path = path.with_suffix(".tmp")

    with open(temp_path, "w", encoding="utf-8") as f:
        json.dump(
            cache,
            f,
            ensure_ascii=False,
            indent=2
        )

    os.replace(temp_path, path)


def cache_is_final(entry):
    if not isinstance(entry, dict):
        return False

    return entry.get("status") in {"found", "not_found"}


# =========================================================
# HTTP request helpers
# =========================================================
_thread_local = threading.local()


def get_session():
    if not hasattr(_thread_local, "session"):
        session = requests.Session()
        session.headers.update({
            "User-Agent": (
                "Mozilla/5.0 "
                "OpenAlex metadata recovery for academic research"
            )
        })
        _thread_local.session = session

    return _thread_local.session


def build_params(params):
    output = dict(params)

    if OPENALEX_MAILTO:
        output["mailto"] = OPENALEX_MAILTO

    if OPENALEX_API_KEY:
        output["api_key"] = OPENALEX_API_KEY

    return output


def request_json(params):
    session = get_session()

    last_error = ""

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            response = session.get(
                OPENALEX_API,
                params=build_params(params),
                timeout=REQUEST_TIMEOUT,
            )

            if response.status_code == 200:
                return {
                    "status": "ok",
                    "data": response.json(),
                    "error": "",
                }

            if response.status_code == 404:
                return {
                    "status": "not_found",
                    "data": None,
                    "error": "HTTP 404",
                }

            if response.status_code == 400:
                return {
                    "status": "bad_request",
                    "data": None,
                    "error": response.text[:500],
                }

            if response.status_code == 429:
                retry_after = response.headers.get("Retry-After")
                wait_seconds = (
                    float(retry_after)
                    if retry_after and retry_after.isdigit()
                    else min(60, 2 ** attempt)
                )

                last_error = "HTTP 429"
                time.sleep(wait_seconds + random.uniform(0.2, 1.0))
                continue

            if response.status_code >= 500:
                last_error = f"HTTP {response.status_code}"
                time.sleep(
                    min(60, 2 ** attempt)
                    + random.uniform(0.2, 1.0)
                )
                continue

            return {
                "status": "error",
                "data": None,
                "error": (
                    f"HTTP {response.status_code}: "
                    f"{response.text[:300]}"
                ),
            }

        except Exception as exc:
            last_error = repr(exc)
            time.sleep(
                min(60, 2 ** attempt)
                + random.uniform(0.2, 1.0)
            )

    return {
        "status": "error",
        "data": None,
        "error": last_error,
    }


# =========================================================
# OpenAlex matching
# =========================================================
def make_cache_entry(status, record=None, error="", method=""):
    return {
        "status": status,
        "record": record,
        "error": error,
        "method": method,
        "updated_at": datetime.now().isoformat(timespec="seconds"),
    }


def fetch_by_doi(doi, cache_snapshot):
    cache_key = f"doi:{doi}"
    cached = cache_snapshot.get(cache_key)

    if cache_is_final(cached):
        return cache_key, cached

    result = request_json({
        "filter": f"doi:{doi}",
        "per-page": 1,
    })

    if result["status"] != "ok":
        return cache_key, make_cache_entry(
            status="error",
            error=result["error"],
            method="doi",
        )

    results = result["data"].get("results", [])

    if not results:
        return cache_key, make_cache_entry(
            status="not_found",
            method="doi",
        )

    return cache_key, make_cache_entry(
        status="found",
        record=results[0],
        method="doi",
    )


def select_title_match(results, query_title, query_year=None):
    if not results:
        return None

    query_norm = normalize_title(query_title)

    candidates = []

    for record in results:
        record_title = (
            record.get("title")
            or record.get("display_name")
            or ""
        )

        record_norm = normalize_title(record_title)

        if not record_norm:
            continue

        similarity = SequenceMatcher(
            None,
            query_norm,
            record_norm
        ).ratio()

        record_year = record.get("publication_year")

        year_bonus = (
            0.01
            if query_year is not None
            and record_year == query_year
            else 0
        )

        candidates.append({
            "record": record,
            "similarity": similarity,
            "score": similarity + year_bonus,
            "exact": query_norm == record_norm,
        })

    if not candidates:
        return None

    exact_candidates = [
        candidate
        for candidate in candidates
        if candidate["exact"]
    ]

    if exact_candidates:
        exact_candidates.sort(
            key=lambda x: x["score"],
            reverse=True
        )
        return exact_candidates[0]["record"]

    candidates.sort(
        key=lambda x: x["score"],
        reverse=True
    )

    best = candidates[0]

    if best["similarity"] >= TITLE_MATCH_THRESHOLD:
        return best["record"]

    return None


def fetch_by_title(title, year, cache_snapshot):
    title_norm = normalize_title(title)
    cache_key = f"title:{title_norm}"

    cached = cache_snapshot.get(cache_key)

    if cache_is_final(cached):
        return cache_key, cached

    # 首选精确标题查询
    result = request_json({
        "search.exact": title,
        "per-page": 10,
    })

    # 某些环境下 exact 参数可能返回 400，回退到普通搜索
    if result["status"] == "bad_request":
        result = request_json({
            "search": title,
            "per-page": 10,
        })

    if result["status"] != "ok":
        return cache_key, make_cache_entry(
            status="error",
            error=result["error"],
            method="title",
        )

    results = result["data"].get("results", [])

    matched = select_title_match(
        results=results,
        query_title=title,
        query_year=year,
    )

    if matched is None:
        return cache_key, make_cache_entry(
            status="not_found",
            method="title",
        )

    return cache_key, make_cache_entry(
        status="found",
        record=matched,
        method="title",
    )


# =========================================================
# Parallel querying
# =========================================================
def run_parallel_fetch(task_function, keys, cache_snapshot, extra=None):
    output = {}

    if not keys:
        return output

    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = {}

        for key in keys:
            if extra is None:
                future = executor.submit(
                    task_function,
                    key,
                    cache_snapshot,
                )
            else:
                future = executor.submit(
                    task_function,
                    key,
                    extra[key],
                    cache_snapshot,
                )

            futures[future] = key

        for future in tqdm(
            as_completed(futures),
            total=len(futures),
            desc=task_function.__name__,
        ):
            key = futures[future]

            try:
                cache_key, entry = future.result()
                output[cache_key] = entry
            except Exception as exc:
                if task_function == fetch_by_doi:
                    cache_key = f"doi:{key}"
                else:
                    cache_key = f"title:{normalize_title(key)}"

                output[cache_key] = make_cache_entry(
                    status="error",
                    error=repr(exc),
                    method=(
                        "doi"
                        if task_function == fetch_by_doi
                        else "title"
                    ),
                )

    return output


# =========================================================
# Read all JSONL files
# =========================================================
file_records = {}
candidates = []

for jsonl_path in TARGET_FILES:
    records = []

    with open(jsonl_path, "r", encoding="utf-8") as f:
        for line_number, line in enumerate(f, start=1):
            line = line.strip()

            if not line:
                continue

            try:
                item = json.loads(line)
            except json.JSONDecodeError as exc:
                print(
                    f"[Warning] Invalid JSON: "
                    f"{jsonl_path.name}:{line_number} | {exc}"
                )
                continue

            records.append(item)

            if not is_openalex_id(item.get("id")):
                candidates.append({
                    "path": jsonl_path,
                    "index": len(records) - 1,
                    "item": item,
                    "old_id": item.get("id", ""),
                    "doi": get_item_doi(item),
                    "title": get_item_title(item),
                    "year": get_item_year(item),
                })

    file_records[jsonl_path] = records


print(f"JSONL files found: {len(TARGET_FILES)}")
print(f"Non-OpenAlex records: {len(candidates)}")


# =========================================================
# Prepare unique queries
# =========================================================
doi_keys = sorted({
    candidate["doi"]
    for candidate in candidates
    if candidate["doi"]
})

title_year_map = {}

for candidate in candidates:
    if candidate["title"]:
        title_key = normalize_title(candidate["title"])
        if title_key:
            title_year_map[title_key] = candidate["year"]

title_keys = sorted(title_year_map.keys())

cache = load_cache(CACHE_PATH)

# 只请求 cache 中没有最终结果的 DOI
missing_doi_keys = [
    doi
    for doi in doi_keys
    if not cache_is_final(cache.get(f"doi:{doi}"))
]

doi_cache_results = run_parallel_fetch(
    task_function=fetch_by_doi,
    keys=missing_doi_keys,
    cache_snapshot=cache,
)

cache.update(doi_cache_results)
save_cache(cache, CACHE_PATH)


# =========================================================
# Title fallback for no DOI or failed DOI lookup
# =========================================================
title_keys_needed = set()

for candidate in candidates:
    doi = candidate["doi"]

    if doi:
        doi_entry = cache.get(f"doi:{doi}")

        if doi_entry and doi_entry.get("status") == "found":
            continue

    title = candidate["title"]

    if title:
        title_keys_needed.add(normalize_title(title))

missing_title_keys = [
    title_key
    for title_key in sorted(title_keys_needed)
    if not cache_is_final(cache.get(f"title:{title_key}"))
]

title_extra = {
    title_key: title_year_map.get(title_key)
    for title_key in missing_title_keys
}

title_cache_results = run_parallel_fetch(
    task_function=fetch_by_title,
    keys=missing_title_keys,
    cache_snapshot=cache,
    extra=title_extra,
)

cache.update(title_cache_results)
save_cache(cache, CACHE_PATH)


# =========================================================
# Replace matched records
# =========================================================
def build_updated_openalex_item(old_item, openalex_record, method):
    new_item = deepcopy(openalex_record)

    old_id = old_item.get("id")

    if old_id:
        new_item["previous_id"] = old_id

    # 保留原始 DBLP 来源信息
    if "dblp_source" in old_item:
        new_item["dblp_source"] = old_item["dblp_source"]

    # 保留原始摘要
    if "reconstructed_abstract" in old_item:
        new_item["reconstructed_abstract"] = (
            old_item["reconstructed_abstract"]
        )

    # 保留与官方来源和后续分析有关的元数据
    preserve_keys = [
        "abstract_source",
        "source_type",
        "official_source_url",
        "conference",
        "year",
        "proceedings_type",
        "proceedings_name",
        "track_type",
        "section/track_name",
    ]

    for key in preserve_keys:
        if key in old_item:
            new_item[key] = old_item[key]

    new_item["openalex_refetch_method"] = method
    new_item["openalex_refetch_time"] = (
        datetime.now().isoformat(timespec="seconds")
    )

    return new_item


report_rows = []
updated_by_file = {}

for candidate in candidates:
    old_item = candidate["item"]
    doi = candidate["doi"]
    title = candidate["title"]

    entry = None
    method = ""

    # DOI 优先
    if doi:
        doi_entry = cache.get(f"doi:{doi}")

        if (
            doi_entry
            and doi_entry.get("status") == "found"
            and doi_entry.get("record")
        ):
            entry = doi_entry
            method = "doi"

    # DOI 未找到或没有 DOI 时使用标题
    if entry is None and title:
        title_key = normalize_title(title)
        title_entry = cache.get(f"title:{title_key}")

        if (
            title_entry
            and title_entry.get("status") == "found"
            and title_entry.get("record")
        ):
            entry = title_entry
            method = "title"

    if entry is not None:
        new_item = build_updated_openalex_item(
            old_item=old_item,
            openalex_record=entry["record"],
            method=method,
        )

        file_records[candidate["path"]][candidate["index"]] = new_item

        updated_by_file.setdefault(candidate["path"], 0)
        updated_by_file[candidate["path"]] += 1

        report_rows.append({
            "file": candidate["path"].name,
            "old_id": candidate["old_id"],
            "new_id": new_item.get("id", ""),
            "doi": doi,
            "title": title,
            "year": candidate["year"],
            "match_status": "found",
            "match_method": method,
            "error": "",
        })

    else:
        errors = []

        if doi:
            doi_entry = cache.get(f"doi:{doi}")
            if doi_entry:
                errors.append(
                    f"doi:{doi_entry.get('status')}:"
                    f"{doi_entry.get('error', '')}"
                )

        if title:
            title_key = normalize_title(title)
            title_entry = cache.get(f"title:{title_key}")
            if title_entry:
                errors.append(
                    f"title:{title_entry.get('status')}:"
                    f"{title_entry.get('error', '')}"
                )

        report_rows.append({
            "file": candidate["path"].name,
            "old_id": candidate["old_id"],
            "new_id": "",
            "doi": doi,
            "title": title,
            "year": candidate["year"],
            "match_status": "unmatched",
            "match_method": "",
            "error": " | ".join(errors),
        })


# =========================================================
# Backup and write updated JSONL files
# =========================================================
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

for jsonl_path, n_updated in updated_by_file.items():
    if n_updated == 0:
        continue

    backup_path = jsonl_path.with_name(
        f"{jsonl_path.name}.bak_before_openalex_refetch_{timestamp}"
    )

    shutil.copy2(jsonl_path, backup_path)

    temp_path = jsonl_path.with_suffix(".tmp")

    with open(temp_path, "w", encoding="utf-8") as f:
        for item in file_records[jsonl_path]:
            f.write(
                json.dumps(
                    item,
                    ensure_ascii=False,
                )
                + "\n"
            )

    os.replace(temp_path, jsonl_path)

    print(
        f"Updated {jsonl_path.name}: {n_updated} records"
    )
    print(f"Backup saved to: {backup_path}")


# =========================================================
# Save reports
# =========================================================
report_df = pd.DataFrame(report_rows)

if not report_df.empty:
    report_df.to_csv(
        REPORT_PATH,
        index=False,
        encoding="utf-8-sig",
    )

    report_df[
        report_df["match_status"] == "unmatched"
    ].to_csv(
        UNMATCHED_PATH,
        index=False,
        encoding="utf-8-sig",
    )


# =========================================================
# Summary
# =========================================================
print("\nProcessing completed.")
print(f"Cache: {CACHE_PATH}")
print(f"Report: {REPORT_PATH}")
print(f"Unmatched: {UNMATCHED_PATH}")

if not report_df.empty:
    print("\nMatch summary:")
    print(report_df["match_status"].value_counts())

    print("\nMatch method summary:")
    print(
        report_df[
            report_df["match_status"] == "found"
        ]["match_method"].value_counts()
    )

print("\nUpdated files:")
for path, count in updated_by_file.items():
    print(f"{path.name}: {count}")

JSONL files found: 10
Non-OpenAlex records: 5077

fetch_by_title:   1%|          | 33/5076 [10:29<26:43:17, 19.08s/it]

#### OpenAlex IJCAI 2024年的数据有问题，DOI是2024的IJCAI的DOI，实际记录的内容是2025年的，所以需要找到这部分论文条目并根据title去查询openalex

In [ ]:
import os
import re
import json
import time
import random
import shutil
import html
import unicodedata
import threading

from pathlib import Path
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed
from difflib import SequenceMatcher

import pandas as pd
import requests
from tqdm.auto import tqdm


# =========================================================
# Configuration
# =========================================================
BASE_DIR = Path(
    "/home/user/GSK/lily/science_of_science/NewDataset/"
    "AI_impact_on_cs_publications/Data"
)

COMBINE_PATH = (
    BASE_DIR
    / "20260712_dblp_source_enrichment"
    / "ijcai_combined_openalex_with_abstract_dblp_enriched.jsonl"
)

REPORT_DIR = COMBINE_PATH.parent

REPORT_PATH = sorted(
    REPORT_DIR.glob("ijcai_dblp_hybrid_repair_report_*.csv")
)[-1]

CACHE_PATH = (
    REPORT_DIR / "ijcai_title_only_refetch_cache.json"
)

OPENALEX_API = "https://api.openalex.org/works"


# 建议填写自己的邮箱，以使用 OpenAlex polite pool
OPENALEX_MAILTO = ""

# 如果有 OpenAlex API key，可以填写；没有则留空
OPENALEX_API_KEY = ""

MAX_WORKERS = 3
MAX_RETRIES = 5
REQUEST_TIMEOUT = 45
TITLE_SIMILARITY_THRESHOLD = 0.98


# =========================================================
# Text normalization
# =========================================================
def normalize_title(title, compact=False):
    """
    保留英文字母、数字和空格，删除其他符号。
    compact=True 时进一步删除空格。
    """
    text = html.unescape(str(title or ""))

    text = unicodedata.normalize("NFKD", text)
    text = "".join(
        char for char in text
        if not unicodedata.combining(char)
    )

    text = re.sub(r"[^0-9a-zA-Z\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip().lower()

    if compact:
        text = text.replace(" ", "")

    return text


def reconstruct_abstract(inverted_index):
    if not isinstance(inverted_index, dict):
        return ""

    positions = []

    for word, indexes in inverted_index.items():
        if not isinstance(indexes, list):
            continue

        for position in indexes:
            try:
                positions.append((int(position), word))
            except Exception:
                continue

    positions.sort(key=lambda x: x[0])
    return " ".join(word for _, word in positions).strip()


# =========================================================
# Cache
# =========================================================
def load_cache():
    if not CACHE_PATH.exists():
        return {}

    try:
        with CACHE_PATH.open("r", encoding="utf-8") as f:
            cache = json.load(f)

        return cache if isinstance(cache, dict) else {}

    except Exception as exc:
        print("Cache loading failed:", repr(exc))
        return {}


def save_cache(cache):
    temp_path = CACHE_PATH.with_suffix(".tmp")

    with temp_path.open("w", encoding="utf-8") as f:
        json.dump(cache, f, ensure_ascii=False, indent=2)

    os.replace(temp_path, CACHE_PATH)


# =========================================================
# HTTP request
# =========================================================
_thread_local = threading.local()


def get_session():
    if not hasattr(_thread_local, "session"):
        session = requests.Session()
        session.headers.update({
            "User-Agent": (
                "OpenAlex title-only recovery for academic research"
            )
        })
        _thread_local.session = session

    return _thread_local.session


def query_openalex_by_title(title):
    """
    只使用标题查询，不使用 DOI。
    """
    session = get_session()

    common_params = {
        "per-page": 10,
        "api_key": OPENALEX_API_KEY,
        "mailto": OPENALEX_MAILTO,
    }

    query_variants = [
        {"search.exact": title},
        {"search": title},
    ]

    last_error = ""

    for query_params in query_variants:
        params = dict(common_params)
        params.update(query_params)

        for attempt in range(1, MAX_RETRIES + 1):
            try:
                response = session.get(
                    OPENALEX_API,
                    params=params,
                    timeout=REQUEST_TIMEOUT,
                )

                if response.status_code == 200:
                    return {
                        "status": "ok",
                        "results": response.json().get("results", []),
                        "query_mode": (
                            "search.exact"
                            if "search.exact" in query_params
                            else "search"
                        ),
                        "error": "",
                    }

                if response.status_code == 400:
                    # search.exact 失败时尝试 search
                    last_error = response.text[:500]
                    break

                if response.status_code == 429:
                    retry_after = response.headers.get("Retry-After")

                    if retry_after and retry_after.isdigit():
                        wait_seconds = float(retry_after)
                    else:
                        wait_seconds = min(60, 2 ** attempt)

                    time.sleep(
                        wait_seconds + random.uniform(0.2, 1.0)
                    )
                    continue

                if response.status_code >= 500:
                    last_error = f"HTTP {response.status_code}"
                    time.sleep(
                        min(60, 2 ** attempt)
                        + random.uniform(0.2, 1.0)
                    )
                    continue

                last_error = (
                    f"HTTP {response.status_code}: "
                    f"{response.text[:500]}"
                )
                break

            except Exception as exc:
                last_error = repr(exc)
                time.sleep(
                    min(60, 2 ** attempt)
                    + random.uniform(0.2, 1.0)
                )

    return {
        "status": "error",
        "results": [],
        "query_mode": "",
        "error": last_error,
    }


# =========================================================
# Select title match
# =========================================================
def select_title_match(results, query_title, target_year=None):
    if not results:
        return None, "not_found", 0.0

    query_key = normalize_title(query_title)
    query_compact_key = normalize_title(
        query_title,
        compact=True,
    )

    candidates = []

    for record in results:
        result_title = (
            record.get("title")
            or record.get("display_name")
            or ""
        )

        result_key = normalize_title(result_title)
        result_compact_key = normalize_title(
            result_title,
            compact=True,
        )

        similarity = SequenceMatcher(
            None,
            query_key,
            result_key,
        ).ratio()

        year_bonus = 0

        if (
            target_year is not None
            and record.get("publication_year") == target_year
        ):
            year_bonus = 0.01

        candidates.append({
            "record": record,
            "exact": result_key == query_key,
            "compact_exact": (
                result_compact_key == query_compact_key
            ),
            "similarity": similarity,
            "score": similarity + year_bonus,
        })

    exact_matches = [
        item for item in candidates
        if item["exact"] or item["compact_exact"]
    ]

    if exact_matches:
        exact_matches.sort(
            key=lambda x: x["score"],
            reverse=True,
        )

        best = exact_matches[0]

        method = (
            "title_exact"
            if best["exact"]
            else "title_compact"
        )

        return (
            best["record"],
            method,
            best["similarity"],
        )

    candidates.sort(
        key=lambda x: x["score"],
        reverse=True,
    )

    best = candidates[0]

    if best["similarity"] >= TITLE_SIMILARITY_THRESHOLD:
        return (
            best["record"],
            "title_fuzzy",
            best["similarity"],
        )

    return (
        None,
        "no_exact_title_match",
        best["similarity"],
    )


def fetch_title_task(title, target_year, cache):
    cache_key = f"title:{normalize_title(title)}"

    cached = cache.get(cache_key)

    if (
        isinstance(cached, dict)
        and cached.get("status") in {"found", "not_found"}
    ):
        return cache_key, cached

    response = query_openalex_by_title(title)

    if response["status"] != "ok":
        return cache_key, {
            "status": "error",
            "record": None,
            "query_title": title,
            "match_method": "",
            "match_score": 0,
            "error": response["error"],
        }

    record, method, score = select_title_match(
        response["results"],
        query_title=title,
        target_year=target_year,
    )

    if record is None:
        return cache_key, {
            "status": "not_found",
            "record": None,
            "query_title": title,
            "match_method": method,
            "match_score": score,
            "error": "",
        }

    return cache_key, {
        "status": "found",
        "record": record,
        "query_title": title,
        "match_method": method,
        "match_score": score,
        "query_mode": response["query_mode"],
        "error": "",
    }


# =========================================================
# Load data
# =========================================================
with COMBINE_PATH.open("r", encoding="utf-8") as f:
    items = [
        json.loads(line)
        for line in f
        if line.strip()
    ]

repair_df = pd.read_csv(REPORT_PATH)

conflict_df = repair_df[
    repair_df["title_consistency"].astype(str).eq("conflict")
].copy()

conflict_record_numbers = (
    conflict_df["record_no"]
    .astype(int)
    .tolist()
)

conflict_tasks = []

for record_no in conflict_record_numbers:
    item = items[record_no - 1]
    dblp_source = item.get("dblp_source")

    if not isinstance(dblp_source, dict):
        continue

    # 使用 DBLP 官方标题查询
    query_title = str(
        dblp_source.get("title") or ""
    ).strip()

    if not query_title:
        continue

    try:
        target_year = int(dblp_source.get("year"))
    except Exception:
        target_year = None

    conflict_tasks.append({
        "record_no": record_no,
        "query_title": query_title,
        "target_year": target_year,
    })

unique_queries = {}

for task in conflict_tasks:
    key = normalize_title(task["query_title"])
    unique_queries[key] = (
        task["query_title"],
        task["target_year"],
    )

print("Conflict records:", len(conflict_tasks))
print("Unique title queries:", len(unique_queries))


# =========================================================
# Fetch all titles
# =========================================================
cache = load_cache()

missing_queries = [
    key
    for key in unique_queries
    if not (
        isinstance(cache.get(f"title:{key}"), dict)
        and cache[f"title:{key}"].get("status")
        in {"found", "not_found"}
    )
]

new_cache_entries = {}

with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
    futures = {}

    for key in missing_queries:
        title, year = unique_queries[key]

        future = executor.submit(
            fetch_title_task,
            title,
            year,
            cache,
        )

        futures[future] = key

    for future in tqdm(
        as_completed(futures),
        total=len(futures),
        desc="OpenAlex title queries",
    ):
        key = futures[future]

        try:
            cache_key, result = future.result()
            new_cache_entries[cache_key] = result
        except Exception as exc:
            new_cache_entries[f"title:{key}"] = {
                "status": "error",
                "record": None,
                "query_title": unique_queries[key][0],
                "match_method": "",
                "match_score": 0,
                "error": repr(exc),
            }

cache.update(new_cache_entries)
save_cache(cache)


# =========================================================
# Update conflict records
# =========================================================
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

backup_path = COMBINE_PATH.with_name(
    f"{COMBINE_PATH.name}.bak_before_title_only_refetch_{timestamp}"
)

report_output_path = COMBINE_PATH.parent / (
    f"ijcai_title_only_refetch_report_{timestamp}.csv"
)

shutil.copy2(COMBINE_PATH, backup_path)

result_rows = []
updated_count = 0
failed_count = 0

for task in conflict_tasks:
    record_no = task["record_no"]
    query_title = task["query_title"]
    cache_key = f"title:{normalize_title(query_title)}"

    cache_entry = cache.get(cache_key, {})
    old_item = items[record_no - 1]

    old_id = old_item.get("id", "")
    old_title = (
        old_item.get("title")
        or old_item.get("display_name")
        or ""
    )

    if (
        cache_entry.get("status") != "found"
        or not isinstance(cache_entry.get("record"), dict)
    ):
        failed_count += 1

        result_rows.append({
            "record_no": record_no,
            "query_title": query_title,
            "old_id": old_id,
            "old_title": old_title,
            "new_id": "",
            "new_title": "",
            "match_status": "failed",
            "match_method": cache_entry.get(
                "match_method",
                "",
            ),
            "match_score": cache_entry.get(
                "match_score",
                0,
            ),
            "abstract_available": False,
            "error": cache_entry.get("error", ""),
        })

        continue

    new_item = dict(cache_entry["record"])

    # 保留 DBLP source
    new_item["dblp_source"] = old_item.get(
        "dblp_source"
    )

    # 使用新 OpenAlex item 的摘要
    reconstructed_abstract = reconstruct_abstract(
        new_item.get("abstract_inverted_index")
    )

    new_item["reconstructed_abstract"] = (
        reconstructed_abstract
    )

    if reconstructed_abstract:
        new_item["abstract_source"] = (
            "openalex_title_only_refetch"
        )
    else:
        new_item["abstract_source"] = (
            "openalex_title_only_refetch_missing_abstract"
        )

    # 保留原来的 DBLP 重复字段
    for field in [
        "proceedings_type",
        "proceedings_name",
        "track_type",
        "section/track_name",
        "source_url",
    ]:
        if field in old_item:
            new_item[field] = old_item[field]

    # 保存替换前信息
    new_item["previous_openalex_id"] = old_id
    new_item["previous_openalex_title"] = old_title
    new_item["openalex_refetch_method"] = "title_only"
    new_item["openalex_refetch_query_title"] = query_title

    items[record_no - 1] = new_item
    updated_count += 1

    result_rows.append({
        "record_no": record_no,
        "query_title": query_title,
        "old_id": old_id,
        "old_title": old_title,
        "new_id": new_item.get("id", ""),
        "new_title": (
            new_item.get("title")
            or new_item.get("display_name")
            or ""
        ),
        "match_status": "found",
        "match_method": cache_entry.get(
            "match_method",
            "",
        ),
        "match_score": cache_entry.get(
            "match_score",
            0,
        ),
        "abstract_available": bool(
            reconstructed_abstract
        ),
        "error": "",
    })


# =========================================================
# Save updated JSONL
# =========================================================
temp_path = COMBINE_PATH.with_suffix(".tmp")

with temp_path.open("w", encoding="utf-8") as f:
    for item in items:
        f.write(
            json.dumps(
                item,
                ensure_ascii=False,
            )
            + "\n"
        )

os.replace(temp_path, COMBINE_PATH)

pd.DataFrame(result_rows).to_csv(
    report_output_path,
    index=False,
    encoding="utf-8-sig",
)


# =========================================================
# Summary
# =========================================================
result_df = pd.DataFrame(result_rows)

print("\nCompleted.")
print("Updated records:", updated_count)
print("Failed records:", failed_count)
print("Updated JSONL:", COMBINE_PATH)
print("Backup:", backup_path)
print("Cache:", CACHE_PATH)
print("Report:", report_output_path)

if not result_df.empty:
    print("\nMatch status:")
    print(result_df["match_status"].value_counts())

    print("\nAbstract coverage:")
    print(result_df["abstract_available"].value_counts())

Conflict records: 967
Unique title queries: 967

OpenAlex title queries: 0it [00:00, ?it/s]

Completed.
Updated records: 303
Failed records: 664
Updated JSONL: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260712_dblp_source_enrichment/ijcai_combined_openalex_with_abstract_dblp_enriched.jsonl
Backup: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260712_dblp_source_enrichment/ijcai_combined_openalex_with_abstract_dblp_enriched.jsonl.bak_before_title_only_refetch_20260714_191441
Cache: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260712_dblp_source_enrichment/ijcai_title_only_refetch_cache.json
Report: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260712_dblp_source_enrichment/ijcai_title_only_refetch_report_20260714_191441.csv

Match status:
match_status
failed    664
found     303
Name: count, dtype: int64

Abstract coverage:
abstract_available
False    667
True     300
Name: count, dtype: int64

In [ ]:
import json
import re
import time
import hashlib
from pathlib import Path
from urllib.parse import quote

import pandas as pd
import requests

try:
    import fitz  # PyMuPDF
except ImportError:
    raise ImportError("请先安装 PyMuPDF：pip install pymupdf")


# =========================================================
# Configuration
# =========================================================

BASE_DIR = Path(
    "/home/user/GSK/lily/science_of_science/NewDataset/"
    "AI_impact_on_cs_publications"
)

INPUT_DIR = (
    BASE_DIR
    / "Data/20260715_coverage_kdd_sigir_www_by_track"
)

PDF_DIR = BASE_DIR / "Data" / "acm_papers"

OUTPUT_DIR = BASE_DIR / "Data/20260716_openalex_main_track_recovery"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

CACHE_PATH = OUTPUT_DIR / "openalex_doi_cache.json"

# 请填写你的信息
OPENALEX_EMAIL = ""
OPENALEX_API_KEY = ""

TARGET_FILES = {
    "KDD": INPUT_DIR / "KDD_main_track_not_in_jsonl.csv",
    "SIGIR": INPUT_DIR / "SIGIR_main_track_not_in_jsonl.csv",
    "WWW": INPUT_DIR / "WWW_main_track_not_in_jsonl.csv",
}

OPENALEX_API = "https://api.openalex.org/works"

REQUEST_TIMEOUT = 30
MAX_RETRIES = 5
SLEEP_SECONDS = 1.0


# =========================================================
# Basic normalization
# =========================================================

def normalize_doi(value):
    if value is None or pd.isna(value):
        return ""

    doi = str(value).strip().lower()

    doi = re.sub(
        r"^https?://(dx\.)?doi\.org/",
        "",
        doi
    )

    doi = re.sub(r"^doi:\s*", "", doi)

    return doi.rstrip(" .;,").strip()


def normalize_text(value):
    if value is None:
        return ""

    text = str(value)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def normalize_title(value):
    if value is None or pd.isna(value):
        return ""

    text = str(value).lower()
    text = re.sub(r"[^0-9a-z]+", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    return text


# =========================================================
# Cache
# =========================================================

def load_cache():
    if not CACHE_PATH.exists():
        return {}

    with open(CACHE_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def save_cache(cache):
    temp_path = CACHE_PATH.with_suffix(".tmp")

    with open(temp_path, "w", encoding="utf-8") as f:
        json.dump(cache, f, ensure_ascii=False, indent=2)

    temp_path.replace(CACHE_PATH)


# =========================================================
# OpenAlex request
# =========================================================

def query_openalex_by_doi(doi):
    """
    通过 DOI 请求 OpenAlex。
    只使用 DOI，不使用标题进行二次搜索。
    """

    doi = normalize_doi(doi)

    if not doi:
        return {
            "status": "invalid_doi",
            "data": None,
            "error": "empty_doi",
        }

    encoded_doi = quote(
        f"https://doi.org/{doi}",
        safe=""
    )

    url = f"{OPENALEX_API}/{encoded_doi}"

    params = {
        "api_key": OPENALEX_API_KEY,
        "mailto": OPENALEX_EMAIL,
    }

    headers = {
        "User-Agent": (
            f"Academic metadata recovery; mailto:{OPENALEX_EMAIL}"
        )
    }

    last_error = ""

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            response = requests.get(
                url,
                params=params,
                headers=headers,
                timeout=REQUEST_TIMEOUT,
            )

            if response.status_code == 200:
                data = response.json()

                if data and data.get("id"):
                    return {
                        "status": "success",
                        "data": data,
                        "error": "",
                    }

                return {
                    "status": "not_found",
                    "data": None,
                    "error": "empty_openalex_response",
                }

            if response.status_code == 404:
                return {
                    "status": "not_found",
                    "data": None,
                    "error": "openalex_404",
                }

            if response.status_code == 429:
                wait_seconds = 10 * attempt
                print(
                    f"[429] DOI={doi}; "
                    f"sleep {wait_seconds}s"
                )
                time.sleep(wait_seconds)
                continue

            if response.status_code in {401, 403}:
                return {
                    "status": "request_failed",
                    "data": None,
                    "error": (
                        f"HTTP {response.status_code}: "
                        "API key or permission problem"
                    ),
                }

            last_error = (
                f"HTTP {response.status_code}: "
                f"{response.text[:300]}"
            )

        except requests.RequestException as exc:
            last_error = repr(exc)

        wait_seconds = SLEEP_SECONDS * attempt
        time.sleep(wait_seconds)

    return {
        "status": "request_failed",
        "data": None,
        "error": last_error,
    }


# =========================================================
# Abstract reconstruction from OpenAlex
# =========================================================

def reconstruct_openalex_abstract(inverted_index):
    if not inverted_index:
        return ""

    positions = []

    for word, indexes in inverted_index.items():
        if not isinstance(indexes, list):
            continue

        for position in indexes:
            positions.append((position, word))

    positions.sort(key=lambda x: x[0])

    return normalize_text(
        " ".join(word for _, word in positions)
    )


# =========================================================
# PDF matching
# =========================================================

def build_pdf_index(pdf_dir):
    """
    建立 PDF 索引。

    优先使用 PDF 文件名中的 DOI。
    同时建立标题索引，作为 DOI 文件名不存在时的备用方法。
    """

    doi_index = {}
    title_index = {}

    if not pdf_dir.exists():
        print(f"[Warning] PDF directory does not exist: {pdf_dir}")
        return doi_index, title_index

    pdf_paths = list(pdf_dir.rglob("*.pdf"))

    print(f"Found {len(pdf_paths)} PDF files.")

    for pdf_path in pdf_paths:
        filename = pdf_path.stem

        # 尝试从文件名中识别 DOI
        doi_candidates = re.findall(
            r"10\.\d{4,9}/[-._;()/:a-z0-9]+",
            filename.lower()
        )

        for doi in doi_candidates:
            doi = normalize_doi(doi)
            if doi:
                doi_index.setdefault(doi, []).append(pdf_path)

        # 使用文件名建立标题索引
        title_key = normalize_title(filename)

        if title_key:
            title_index.setdefault(title_key, []).append(pdf_path)

    return doi_index, title_index


PDF_DOI_INDEX, PDF_TITLE_INDEX = build_pdf_index(PDF_DIR)


def find_pdf(doi, title):
    doi = normalize_doi(doi)

    if doi and doi in PDF_DOI_INDEX:
        return PDF_DOI_INDEX[doi][0], "doi_filename"

    title_key = normalize_title(title)

    if title_key and title_key in PDF_TITLE_INDEX:
        return PDF_TITLE_INDEX[title_key][0], "title_filename"

    # 文件名可能包含额外信息，因此进行保守的标题包含匹配
    if title_key:
        for key, paths in PDF_TITLE_INDEX.items():
            if len(title_key) > 30:
                if title_key in key or key in title_key:
                    return paths[0], "title_partial"

    return None, "pdf_not_found"


# =========================================================
# Extract abstract from PDF
# =========================================================

def clean_pdf_text(text):
    text = text.replace("\u00ad", "")
    text = re.sub(r"-\s*\n\s*", "", text)
    text = re.sub(r"\n+", "\n", text)
    text = re.sub(r"[ \t]+", " ", text)

    return text.strip()


def extract_abstract_from_pdf(pdf_path):
    """
    从 PDF 前三页中提取 Abstract 段落。
    """

    try:
        doc = fitz.open(pdf_path)
    except Exception as exc:
        return "", f"pdf_open_error: {exc}"

    pages = []

    try:
        max_pages = min(3, len(doc))

        for page_index in range(max_pages):
            text = doc[page_index].get_text("text")
            if text:
                pages.append(text)

    finally:
        doc.close()

    text = clean_pdf_text("\n".join(pages))

    if not text:
        return "", "empty_pdf_text"

    # 支持 Abstract / ABSTRACT / Abstract.
    match = re.search(
        r"\babstract\b\s*[:.]?\s*",
        text,
        flags=re.IGNORECASE
    )

    if not match:
        return "", "abstract_marker_not_found"

    abstract_text = text[match.end():]

    # Abstract 后常见的下一个章节标题
    stop_patterns = [
        r"\n\s*1\s+Introduction\b",
        r"\n\s*Introduction\b",
        r"\n\s*1\.\s+Introduction\b",
        r"\n\s*Keywords?\b",
        r"\n\s*CCS Concepts?\b",
        r"\n\s*Categories and Subject Descriptors\b",
    ]

    stop_positions = []

    for pattern in stop_patterns:
        stop_match = re.search(
            pattern,
            abstract_text,
            flags=re.IGNORECASE
        )
        if stop_match:
            stop_positions.append(stop_match.start())

    if stop_positions:
        abstract_text = abstract_text[:min(stop_positions)]

    abstract_text = normalize_text(abstract_text)

    # 删除过短或明显不是摘要的结果
    if len(abstract_text.split()) < 20:
        return "", "abstract_too_short"

    return abstract_text, "pdf_abstract"


# =========================================================
# Process one paper
# =========================================================

def process_paper(row, cache):
    doi = normalize_doi(row.get("doi"))
    title = normalize_text(row.get("title"))

    if not doi:
        return {
            "status": "invalid_doi",
            "openalex": None,
            "abstract": "",
            "abstract_source": "none",
            "pdf_path": "",
            "pdf_match_method": "",
            "error": "missing_doi",
        }

    # DOI 作为 cache key
    if doi in cache:
        oa_result = cache[doi]
    else:
        oa_result = query_openalex_by_doi(doi)
        cache[doi] = oa_result
        save_cache(cache)

    if oa_result["status"] != "success":
        return {
            "status": oa_result["status"],
            "openalex": None,
            "abstract": "",
            "abstract_source": "none",
            "pdf_path": "",
            "pdf_match_method": "",
            "error": oa_result.get("error", ""),
        }

    openalex_item = oa_result["data"]

    # 只从 ACM PDF 提取摘要
    pdf_path, pdf_match_method = find_pdf(
        doi=doi,
        title=title,
    )

    abstract = ""
    abstract_source = "none"
    abstract_error = ""

    if pdf_path is not None:
        abstract, abstract_source = extract_abstract_from_pdf(pdf_path)
        if not abstract:
            abstract_error = abstract_source

    # 如果 PDF 没有成功提取，使用 OpenAlex inverted index 作为备用
    if not abstract:
        abstract = reconstruct_openalex_abstract(
            openalex_item.get("abstract_inverted_index")
        )

        if abstract:
            abstract_source = "openalex_abstract_inverted_index"
        else:
            abstract_source = "none"

    return {
        "status": "success",
        "openalex": openalex_item,
        "abstract": abstract,
        "abstract_source": abstract_source,
        "pdf_path": str(pdf_path) if pdf_path else "",
        "pdf_match_method": pdf_match_method,
        "error": abstract_error,
    }


# =========================================================
# Main processing
# =========================================================

cache = load_cache()

for conference, input_path in TARGET_FILES.items():
    if not input_path.exists():
        print(f"[Warning] Missing input file: {input_path}")
        continue

    df = pd.read_csv(input_path, low_memory=False)

    required_columns = {"doi", "title"}
    missing_columns = required_columns - set(df.columns)

    if missing_columns:
        raise ValueError(
            f"{input_path.name} missing columns: {missing_columns}"
        )

    output_jsonl = (
        OUTPUT_DIR
        / f"{conference.lower()}_main_track_openalex_recovered.jsonl"
    )

    output_report = (
        OUTPUT_DIR
        / f"{conference.lower()}_main_track_openalex_recovery_report.csv"
    )

    report_rows = []
    success_count = 0
    failed_count = 0

    with open(output_jsonl, "w", encoding="utf-8") as fout:
        for index, row in df.iterrows():
            result = process_paper(row, cache)

            original_row = row.to_dict()
            dblp_source = original_row.copy()

            if result["openalex"] is not None:
                item = dict(result["openalex"])

                # 保存原始 DBLP 信息
                item["dblp_source"] = dblp_source

                # 添加重构摘要
                item["reconstructed_abstract"] = result["abstract"]
                item["abstract_source"] = result["abstract_source"]

                # 保存恢复过程信息
                item["openalex_recovery_method"] = "doi"
                item["openalex_recovery_query_doi"] = normalize_doi(
                    row.get("doi")
                )
                item["pdf_path"] = result["pdf_path"]
                item["pdf_match_method"] = result["pdf_match_method"]

                fout.write(
                    json.dumps(
                        item,
                        ensure_ascii=False
                    )
                    + "\n"
                )

                success_count += 1

            else:
                failed_count += 1

            report_rows.append({
                "conference": conference,
                "row_index": int(index),
                "doi": normalize_doi(row.get("doi")),
                "title": row.get("title"),
                "openalex_status": result["status"],
                "abstract_source": result["abstract_source"],
                "pdf_path": result["pdf_path"],
                "pdf_match_method": result["pdf_match_method"],
                "error": result["error"],
            })

    report_df = pd.DataFrame(report_rows)
    report_df.to_csv(
        output_report,
        index=False,
        encoding="utf-8-sig"
    )

    print(
        f"{conference}: "
        f"success={success_count}, "
        f"failed={failed_count}, "
        f"output={output_jsonl}"
    )

save_cache(cache)

print("Finished.")
print("Cache:", CACHE_PATH)
print("Output directory:", OUTPUT_DIR)

Found 112 PDF files.
KDD: success=57, failed=3, output=/home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260716_openalex_main_track_recovery/kdd_main_track_openalex_recovered.jsonl
SIGIR: success=22, failed=1, output=/home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260716_openalex_main_track_recovery/sigir_main_track_openalex_recovered.jsonl
WWW: success=30, failed=0, output=/home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260716_openalex_main_track_recovery/www_main_track_openalex_recovered.jsonl
Finished.
Cache: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260716_openalex_main_track_recovery/openalex_doi_cache.json
Output directory: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260716_openalex_main_track_recovery

In [ ]:
import json
import re
import time
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed

import pandas as pd
import requests


# =========================================================
# Configuration
# =========================================================

BASE_DIR = Path(
    "/home/user/GSK/lily/science_of_science/NewDataset/"
    "AI_impact_on_cs_publications"
)

INPUT_DIR = (
    BASE_DIR
    / "Data/20260715_coverage_all_conferences_by_track"
)

OUTPUT_DIR = (
    BASE_DIR
    / "Data/20260716_openalex_non_main_track_recovery"
)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# 请填写你的 OpenAlex API 信息
OPENALEX_EMAIL = ""
OPENALEX_API_KEY = ""

OPENALEX_API = "https://api.openalex.org/works"

MAX_WORKERS = 4
MAX_RETRIES = 5
REQUEST_TIMEOUT = 30

CACHE_PATH = OUTPUT_DIR / "openalex_doi_cache.json"


# =========================================================
# Normalization
# =========================================================

def normalize_doi(value):
    if value is None or pd.isna(value):
        return ""

    doi = str(value).strip().lower()

    doi = re.sub(
        r"^https?://(dx\.)?doi\.org/",
        "",
        doi
    )

    doi = re.sub(r"^doi:\s*", "", doi)

    return doi.rstrip(" .;,").strip()


def reconstruct_abstract(inverted_index):
    if not inverted_index:
        return ""

    word_positions = []

    for word, positions in inverted_index.items():
        if not isinstance(positions, list):
            continue

        for position in positions:
            word_positions.append((position, word))

    word_positions.sort(key=lambda x: x[0])

    return " ".join(
        word for _, word in word_positions
    ).strip()


# =========================================================
# Cache
# =========================================================

def load_cache():
    if not CACHE_PATH.exists():
        return {}

    with open(CACHE_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def save_cache(cache):
    temp_path = CACHE_PATH.with_suffix(".tmp")

    with open(temp_path, "w", encoding="utf-8") as f:
        json.dump(
            cache,
            f,
            ensure_ascii=False,
            indent=2
        )

    temp_path.replace(CACHE_PATH)


# =========================================================
# OpenAlex request
# =========================================================

def fetch_openalex_by_doi(doi):
    doi = normalize_doi(doi)

    if not doi:
        return {
            "doi": "",
            "status": "missing_doi",
            "data": None,
            "error": "missing_doi",
        }

    url = (
        f"{OPENALEX_API}/"
        f"https://doi.org/{doi}"
    )

    params = {
        "api_key": OPENALEX_API_KEY,
        "mailto": OPENALEX_EMAIL,
    }

    headers = {
        "User-Agent": (
            f"Academic metadata recovery; "
            f"mailto:{OPENALEX_EMAIL}"
        )
    }

    last_error = ""

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            response = requests.get(
                url,
                params=params,
                headers=headers,
                timeout=REQUEST_TIMEOUT,
            )

            if response.status_code == 200:
                data = response.json()

                if data and data.get("id"):
                    return {
                        "doi": doi,
                        "status": "success",
                        "data": data,
                        "error": "",
                    }

                return {
                    "doi": doi,
                    "status": "not_found",
                    "data": None,
                    "error": "empty_response",
                }

            if response.status_code == 404:
                return {
                    "doi": doi,
                    "status": "not_found",
                    "data": None,
                    "error": "openalex_404",
                }

            if response.status_code == 429:
                wait_seconds = 10 * attempt

                print(
                    f"[429] {doi}; "
                    f"sleeping {wait_seconds}s"
                )

                time.sleep(wait_seconds)
                continue

            if response.status_code in {401, 403}:
                return {
                    "doi": doi,
                    "status": "request_failed",
                    "data": None,
                    "error": (
                        f"HTTP {response.status_code}; "
                        "check API key or permission"
                    ),
                }

            last_error = (
                f"HTTP {response.status_code}: "
                f"{response.text[:300]}"
            )

        except requests.RequestException as exc:
            last_error = repr(exc)

        time.sleep(2 * attempt)

    return {
        "doi": doi,
        "status": "request_failed",
        "data": None,
        "error": last_error,
    }


# =========================================================
# Process one conference file
# =========================================================

def infer_conference(path):
    name = path.name.lower()

    match = re.match(
        r"([a-z]+)_non_main_track_not_in_jsonl\.csv",
        name
    )

    if match:
        return match.group(1).upper()

    return path.stem.upper()


def process_conference(input_path, cache):
    conference = infer_conference(input_path)

    df = pd.read_csv(
        input_path,
        low_memory=False
    )

    if "doi" not in df.columns:
        raise ValueError(
            f"{input_path.name} does not contain a DOI column"
        )

    df["doi_normalized"] = df["doi"].map(normalize_doi)

    doi_df = df[
        df["doi_normalized"].astype(bool)
    ].copy()

    no_doi_df = df[
        ~df["doi_normalized"].astype(bool)
    ].copy()

    unique_dois = (
        doi_df["doi_normalized"]
        .drop_duplicates()
        .tolist()
    )

    print(
        f"{conference}: "
        f"total={len(df)}, "
        f"with_doi={len(doi_df)}, "
        f"without_doi={len(no_doi_df)}"
    )

    # 只请求 cache 中不存在的 DOI
    missing_dois = [
        doi for doi in unique_dois
        if doi not in cache
    ]

    print(
        f"{conference}: "
        f"cached={len(unique_dois) - len(missing_dois)}, "
        f"to_request={len(missing_dois)}"
    )

    # 并发请求 OpenAlex
    with ThreadPoolExecutor(
        max_workers=MAX_WORKERS
    ) as executor:

        futures = {
            executor.submit(
                fetch_openalex_by_doi,
                doi
            ): doi
            for doi in missing_dois
        }

        for future in as_completed(futures):
            doi = futures[future]

            try:
                result = future.result()
            except Exception as exc:
                result = {
                    "doi": doi,
                    "status": "request_failed",
                    "data": None,
                    "error": repr(exc),
                }

            cache[doi] = result

            # 定期保存 cache，避免中断后丢失进度
            if len(cache) % 20 == 0:
                save_cache(cache)

    save_cache(cache)

    recovered_records = []
    report_rows = []

    for _, row in doi_df.iterrows():
        doi = row["doi_normalized"]
        result = cache.get(doi, {})

        status = result.get("status")
        openalex_item = result.get("data")

        if status == "success" and openalex_item:
            item = dict(openalex_item)

            # 删除内部使用的 cache 信息
            item.pop("_cache_status", None)

            # 保存完整 DBLP 信息
            dblp_source = {
                key: (
                    None
                    if pd.isna(value)
                    else value
                )
                for key, value in row.to_dict().items()
                if key != "doi_normalized"
            }

            item["dblp_source"] = dblp_source

            # 重构摘要
            reconstructed_abstract = (
                reconstruct_abstract(
                    item.get("abstract_inverted_index")
                )
            )

            item["reconstructed_abstract"] = (
                reconstructed_abstract
            )

            if reconstructed_abstract:
                item["abstract_source"] = (
                    "openalex_abstract_inverted_index"
                )
            else:
                item["abstract_source"] = "none"

            item["openalex_recovery_method"] = (
                "doi_non_main_track"
            )

            recovered_records.append(item)

            report_rows.append({
                "conference": conference,
                "doi": doi,
                "title": row.get("title", ""),
                "status": "recovered",
                "openalex_id": item.get("id", ""),
                "has_abstract": bool(
                    reconstructed_abstract
                ),
                "error": "",
            })

        else:
            report_rows.append({
                "conference": conference,
                "doi": doi,
                "title": row.get("title", ""),
                "status": status,
                "openalex_id": "",
                "has_abstract": False,
                "error": result.get("error", ""),
            })

    output_jsonl = (
        OUTPUT_DIR
        / f"{conference.lower()}_non_main_track_openalex_recovered.jsonl"
    )

    output_report = (
        OUTPUT_DIR
        / f"{conference.lower()}_non_main_track_openalex_recovery_report.csv"
    )

    with open(output_jsonl, "w", encoding="utf-8") as f:
        for item in recovered_records:
            f.write(
                json.dumps(
                    item,
                    ensure_ascii=False
                )
                + "\n"
            )

    # 将无 DOI 的论文也记录到 report
    for _, row in no_doi_df.iterrows():
        report_rows.append({
            "conference": conference,
            "doi": "",
            "title": row.get("title", ""),
            "status": "missing_doi",
            "openalex_id": "",
            "has_abstract": False,
            "error": "No DOI available",
        })

    pd.DataFrame(report_rows).to_csv(
        output_report,
        index=False,
        encoding="utf-8-sig"
    )

    print(
        f"{conference}: "
        f"recovered={len(recovered_records)}, "
        f"report={output_report.name}"
    )


# =========================================================
# Main
# =========================================================

cache = load_cache()

input_files = sorted(
    INPUT_DIR.glob(
        "*_non_main_track_not_in_jsonl.csv"
    )
)

if not input_files:
    raise FileNotFoundError(
        "No *_non_main_track_not_in_jsonl.csv files found."
    )

for input_path in input_files:
    process_conference(
        input_path=input_path,
        cache=cache
    )

save_cache(cache)

print("\nFinished.")
print("Cache:", CACHE_PATH)
print("Output directory:", OUTPUT_DIR)

AAAI: total=275, with_doi=28, without_doi=247
AAAI: cached=0, to_request=28
AAAI: recovered=27, report=aaai_non_main_track_openalex_recovery_report.csv
ACL: total=26, with_doi=26, without_doi=0
ACL: cached=0, to_request=26
ACL: recovered=26, report=acl_non_main_track_openalex_recovery_report.csv
CVPR: total=70, with_doi=48, without_doi=22
CVPR: cached=0, to_request=48
CVPR: recovered=45, report=cvpr_non_main_track_openalex_recovery_report.csv
EMNLP: total=10, with_doi=10, without_doi=0
EMNLP: cached=0, to_request=10
EMNLP: recovered=10, report=emnlp_non_main_track_openalex_recovery_report.csv
IJCAI: total=145, with_doi=80, without_doi=65
IJCAI: cached=0, to_request=80
IJCAI: recovered=79, report=ijcai_non_main_track_openalex_recovery_report.csv
KDD: total=38, with_doi=27, without_doi=11
KDD: cached=0, to_request=27
KDD: recovered=27, report=kdd_non_main_track_openalex_recovery_report.csv
SIGIR: total=38, with_doi=14, without_doi=24
SIGIR: cached=0, to_request=14
SIGIR: recovered=14, report=sigir_non_main_track_openalex_recovery_report.csv
WWW: total=36, with_doi=20, without_doi=16
WWW: cached=0, to_request=20
WWW: recovered=19, report=www_non_main_track_openalex_recovery_report.csv

Finished.
Cache: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260716_openalex_non_main_track_recovery/openalex_doi_cache.json
Output directory: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260716_openalex_non_main_track_recovery

In [ ]:
import json
import re
import time
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed

import pandas as pd
import requests


# =========================================================
# Configuration
# =========================================================

BASE_DIR = Path(
    "/home/user/GSK/lily/science_of_science/NewDataset/"
    "AI_impact_on_cs_publications"
)

INPUT_DIR = (
    BASE_DIR
    / "Data/20260715_coverage_all_conferences_by_track_after_append"
)

OUTPUT_DIR = (
    BASE_DIR
    / "Data/20260716_openalex_non_main_track_doi_title_recovery"
)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# 请填写你的 OpenAlex 信息
OPENALEX_EMAIL = ""
OPENALEX_API_KEY = ""

OPENALEX_WORKS_API = "https://api.openalex.org/works"

MAX_WORKERS = 4
MAX_RETRIES = 5
REQUEST_TIMEOUT = 30

CACHE_PATH = OUTPUT_DIR / "openalex_doi_title_cache.json"


# =========================================================
# Normalization
# =========================================================

def normalize_doi(value):
    if value is None or pd.isna(value):
        return ""

    doi = str(value).strip().lower()

    doi = re.sub(
        r"^https?://(dx\.)?doi\.org/",
        "",
        doi
    )

    doi = re.sub(r"^doi:\s*", "", doi)

    return doi.rstrip(" .;,").strip()


def normalize_title(value):
    if value is None or pd.isna(value):
        return ""

    title = re.sub(
        r"[^0-9A-Za-z]",
        " ",
        str(value)
    )

    return re.sub(
        r"\s+",
        " ",
        title
    ).strip().lower()


def reconstruct_abstract(inverted_index):
    if not inverted_index:
        return ""

    word_positions = []

    for word, positions in inverted_index.items():
        if not isinstance(positions, list):
            continue

        for position in positions:
            word_positions.append((position, word))

    word_positions.sort(key=lambda x: x[0])

    return " ".join(
        word for _, word in word_positions
    ).strip()


# =========================================================
# Cache
# =========================================================

def load_cache():
    if not CACHE_PATH.exists():
        return {}

    with open(CACHE_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def save_cache(cache):
    temp_path = CACHE_PATH.with_suffix(".tmp")

    with open(temp_path, "w", encoding="utf-8") as f:
        json.dump(
            cache,
            f,
            ensure_ascii=False,
            indent=2
        )

    temp_path.replace(CACHE_PATH)


# =========================================================
# OpenAlex requests
# =========================================================

def request_openalex_by_doi(doi):
    """
    通过 DOI 请求 OpenAlex。
    """

    doi = normalize_doi(doi)

    if not doi:
        return {
            "status": "missing_doi",
            "query_type": "doi",
            "query": "",
            "data": None,
            "error": "empty_doi",
        }

    encoded_url = (
        f"{OPENALEX_WORKS_API}/"
        f"https://doi.org/{doi}"
    )

    params = {
        "api_key": OPENALEX_API_KEY,
        "mailto": OPENALEX_EMAIL,
    }

    headers = {
        "User-Agent": (
            f"Academic metadata recovery; "
            f"mailto:{OPENALEX_EMAIL}"
        )
    }

    last_error = ""

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            response = requests.get(
                encoded_url,
                params=params,
                headers=headers,
                timeout=REQUEST_TIMEOUT,
            )

            if response.status_code == 200:
                data = response.json()

                if data and data.get("id"):
                    return {
                        "status": "success",
                        "query_type": "doi",
                        "query": doi,
                        "data": data,
                        "error": "",
                    }

                return {
                    "status": "not_found",
                    "query_type": "doi",
                    "query": doi,
                    "data": None,
                    "error": "empty_response",
                }

            if response.status_code == 404:
                return {
                    "status": "not_found",
                    "query_type": "doi",
                    "query": doi,
                    "data": None,
                    "error": "openalex_404",
                }

            if response.status_code == 429:
                wait_seconds = 10 * attempt
                print(
                    f"[429 DOI] {doi}; "
                    f"sleep {wait_seconds}s"
                )
                time.sleep(wait_seconds)
                continue

            if response.status_code in {401, 403}:
                return {
                    "status": "request_failed",
                    "query_type": "doi",
                    "query": doi,
                    "data": None,
                    "error": (
                        f"HTTP {response.status_code}; "
                        "check API key or permission"
                    ),
                }

            last_error = (
                f"HTTP {response.status_code}: "
                f"{response.text[:300]}"
            )

        except requests.RequestException as exc:
            last_error = repr(exc)

        time.sleep(2 * attempt)

    return {
        "status": "request_failed",
        "query_type": "doi",
        "query": doi,
        "data": None,
        "error": last_error,
    }


def request_openalex_by_title(title):
    """
    通过 exact title 请求 OpenAlex。
    """

    title = str(title or "").strip()

    if not title:
        return {
            "status": "missing_title",
            "query_type": "title",
            "query": "",
            "data": None,
            "error": "empty_title",
        }

    params = {
        "search.exact": title,
        "per-page": 10,
        "api_key": OPENALEX_API_KEY,
        "mailto": OPENALEX_EMAIL,
    }

    headers = {
        "User-Agent": (
            f"Academic metadata recovery; "
            f"mailto:{OPENALEX_EMAIL}"
        )
    }

    last_error = ""

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            response = requests.get(
                OPENALEX_WORKS_API,
                params=params,
                headers=headers,
                timeout=REQUEST_TIMEOUT,
            )

            if response.status_code == 200:
                payload = response.json()
                results = payload.get("results", [])

                if not results:
                    return {
                        "status": "not_found",
                        "query_type": "title",
                        "query": title,
                        "data": None,
                        "error": "empty_results",
                    }

                normalized_query = normalize_title(title)

                # 优先选择标准化标题完全一致的结果
                exact_matches = [
                    item for item in results
                    if normalize_title(
                        item.get("title")
                        or item.get("display_name")
                    ) == normalized_query
                ]

                selected = (
                    exact_matches[0]
                    if exact_matches
                    else results[0]
                )

                return {
                    "status": "success",
                    "query_type": "title",
                    "query": title,
                    "data": selected,
                    "error": "",
                    "n_results": len(results),
                    "exact_title_match": bool(exact_matches),
                }

            if response.status_code == 429:
                wait_seconds = 10 * attempt
                print(
                    f"[429 TITLE] {title}; "
                    f"sleep {wait_seconds}s"
                )
                time.sleep(wait_seconds)
                continue

            if response.status_code in {401, 403}:
                return {
                    "status": "request_failed",
                    "query_type": "title",
                    "query": title,
                    "data": None,
                    "error": (
                        f"HTTP {response.status_code}; "
                        "check API key or permission"
                    ),
                }

            last_error = (
                f"HTTP {response.status_code}: "
                f"{response.text[:300]}"
            )

        except requests.RequestException as exc:
            last_error = repr(exc)

        time.sleep(2 * attempt)

    return {
        "status": "request_failed",
        "query_type": "title",
        "query": title,
        "data": None,
        "error": last_error,
    }


# =========================================================
# Query wrapper
# =========================================================

def request_one(row_dict):
    doi = normalize_doi(row_dict.get("doi"))
    title = str(row_dict.get("title") or "").strip()

    if doi:
        cache_key = f"doi::{doi}"
        result = request_openalex_by_doi(doi)
    else:
        cache_key = f"title::{normalize_title(title)}"
        result = request_openalex_by_title(title)

    return cache_key, result


# =========================================================
# Process one conference file
# =========================================================

def infer_conference(path):
    match = re.match(
        r"([a-z]+)_non_main_track_not_in_jsonl\.csv",
        path.name.lower()
    )

    if match:
        return match.group(1).upper()

    return path.stem.upper()


def process_file(input_path, cache):
    conference = infer_conference(input_path)

    df = pd.read_csv(
        input_path,
        low_memory=False
    )

    if "title" not in df.columns:
        raise ValueError(
            f"{input_path.name} does not contain title column"
        )

    rows = [
        row.to_dict()
        for _, row in df.iterrows()
    ]

    unique_queries = {}

    for row in rows:
        doi = normalize_doi(row.get("doi"))
        title = str(row.get("title") or "").strip()

        if doi:
            key = f"doi::{doi}"
        else:
            key = f"title::{normalize_title(title)}"

        unique_queries[key] = row

    pending_rows = [
        row for key, row in unique_queries.items()
        if key not in cache
    ]

    print(
        f"{conference}: total={len(rows)}, "
        f"unique_queries={len(unique_queries)}, "
        f"cached={len(unique_queries) - len(pending_rows)}, "
        f"pending={len(pending_rows)}"
    )

    # 并发请求
    with ThreadPoolExecutor(
    max_workers=MAX_WORKERS
) as executor:

        futures = {
            executor.submit(
                request_one,
                row
            ): row
            for row in pending_rows
        }

        completed = 0

        for future in as_completed(futures):
            key, result = future.result()

            # 仅由主线程修改 cache
            cache[key] = result

            completed += 1

            if completed % 20 == 0:
                save_cache(cache)
                print(
                    f"{conference}: "
                    f"{completed}/{len(pending_rows)} requests completed"
                )
    recovered_records = []
    report_rows = []

    for row in rows:
        doi = normalize_doi(row.get("doi"))
        title = str(row.get("title") or "").strip()

        if doi:
            cache_key = f"doi::{doi}"
        else:
            cache_key = f"title::{normalize_title(title)}"

        result = cache.get(cache_key, {})
        status = result.get("status")
        openalex_item = result.get("data")

        if status == "success" and openalex_item:
            item = dict(openalex_item)

            # 保存完整的 DBLP 信息
            dblp_source = {
                key: (
                    None
                    if pd.isna(value)
                    else value
                )
                for key, value in row.items()
            }

            item["dblp_source"] = dblp_source

            # 重构 OpenAlex 摘要
            abstract = reconstruct_abstract(
                item.get("abstract_inverted_index")
            )

            item["reconstructed_abstract"] = abstract

            if abstract:
                item["abstract_source"] = (
                    "openalex_abstract_inverted_index"
                )
            else:
                item["abstract_source"] = "none"

            item["openalex_recovery_method"] = (
                "doi" if doi else "title"
            )

            item["openalex_recovery_query"] = (
                doi if doi else title
            )

            recovered_records.append(item)

            report_rows.append({
                "conference": conference,
                "title": title,
                "doi": doi,
                "query_type": (
                    "doi" if doi else "title"
                ),
                "status": "recovered",
                "openalex_id": item.get("id", ""),
                "has_abstract": bool(abstract),
                "exact_title_match": result.get(
                    "exact_title_match",
                    ""
                ),
                "error": "",
            })

        else:
            report_rows.append({
                "conference": conference,
                "title": title,
                "doi": doi,
                "query_type": (
                    "doi" if doi else "title"
                ),
                "status": status,
                "openalex_id": "",
                "has_abstract": False,
                "exact_title_match": result.get(
                    "exact_title_match",
                    ""
                ),
                "error": result.get("error", ""),
            })

    output_jsonl = (
        OUTPUT_DIR
        / f"{conference.lower()}_non_main_track_openalex_recovered.jsonl"
    )

    output_report = (
        OUTPUT_DIR
        / f"{conference.lower()}_non_main_track_openalex_recovery_report.csv"
    )

    with open(output_jsonl, "w", encoding="utf-8") as f:
        for item in recovered_records:
            f.write(
                json.dumps(
                    item,
                    ensure_ascii=False
                )
                + "\n"
            )

    pd.DataFrame(report_rows).to_csv(
        output_report,
        index=False,
        encoding="utf-8-sig"
    )

    print(
        f"{conference}: "
        f"recovered={len(recovered_records)}, "
        f"report={output_report.name}"
    )


# =========================================================
# Main
# =========================================================

cache = load_cache()

input_files = sorted(
    INPUT_DIR.glob(
        "*_non_main_track_not_in_jsonl.csv"
    )
)

if not input_files:
    raise FileNotFoundError(
        "No *_non_main_track_not_in_jsonl.csv files found."
    )

for input_path in input_files:
    process_file(
        input_path=input_path,
        cache=cache
    )

save_cache(cache)

print("\nFinished.")
print("Cache:", CACHE_PATH)
print("Output directory:", OUTPUT_DIR)

AAAI: total=270, unique_queries=270, cached=100, pending=170
AAAI: 20/170 requests completed
AAAI: 40/170 requests completed
AAAI: 60/170 requests completed
AAAI: 80/170 requests completed
AAAI: 100/170 requests completed
AAAI: 120/170 requests completed
AAAI: 140/170 requests completed
AAAI: 160/170 requests completed
AAAI: recovered=261, report=aaai_non_main_track_openalex_recovery_report.csv
ACL: total=19, unique_queries=19, cached=0, pending=19
ACL: recovered=19, report=acl_non_main_track_openalex_recovery_report.csv
CVPR: total=54, unique_queries=54, cached=0, pending=54
CVPR: 20/54 requests completed
CVPR: 40/54 requests completed
CVPR: recovered=48, report=cvpr_non_main_track_openalex_recovery_report.csv
EMNLP: total=8, unique_queries=8, cached=0, pending=8
EMNLP: recovered=8, report=emnlp_non_main_track_openalex_recovery_report.csv
IJCAI: total=145, unique_queries=145, cached=0, pending=145
IJCAI: 20/145 requests completed
IJCAI: 40/145 requests completed
IJCAI: 60/145 requests completed
IJCAI: 80/145 requests completed
IJCAI: 100/145 requests completed
IJCAI: 120/145 requests completed
IJCAI: 140/145 requests completed
IJCAI: recovered=143, report=ijcai_non_main_track_openalex_recovery_report.csv
KDD: total=38, unique_queries=38, cached=0, pending=38
KDD: 20/38 requests completed
KDD: recovered=38, report=kdd_non_main_track_openalex_recovery_report.csv
SIGIR: total=35, unique_queries=35, cached=0, pending=35
SIGIR: 20/35 requests completed
SIGIR: recovered=35, report=sigir_non_main_track_openalex_recovery_report.csv
WWW: total=36, unique_queries=36, cached=0, pending=36
WWW: 20/36 requests completed
WWW: recovered=34, report=www_non_main_track_openalex_recovery_report.csv

Finished.
Cache: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260716_openalex_non_main_track_doi_title_recovery/openalex_doi_title_cache.json
Output directory: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260716_openalex_non_main_track_doi_title_recovery

In [14]:
import json
import re
from pathlib import Path

import pandas as pd
from tqdm import tqdm


# ============================================================
# Paths
# ============================================================
PROJECT_ROOT = Path(
    "/home/user/GSK/lily/science_of_science/NewDataset/"
    "AI_impact_on_cs_publications"
)

RECOVERY_DIR = (
    PROJECT_ROOT
    / "Data/20260716_openalex_non_main_track_doi_title_recovery"
)

MISSING_DIR = (
    PROJECT_ROOT
    / "Data/20260715_coverage_all_conferences_by_track_after_append"
)

OUT_DIR = RECOVERY_DIR / "classified_results"
OUT_DIR.mkdir(parents=True, exist_ok=True)

WITH_ABSTRACT_PATH = OUT_DIR / (
    "non_main_track_recovery_with_abstract.jsonl"
)

WITHOUT_ABSTRACT_PATH = OUT_DIR / (
    "non_main_track_recovery_without_abstract.jsonl"
)

TITLE_NOT_EXACT_PATH = OUT_DIR / (
    "non_main_track_recovery_title_not_exact.csv"
)

SUMMARY_PATH = OUT_DIR / "recovery_summary.csv"

GROUP_SUMMARY_PATH = OUT_DIR / (
    "recovery_group_summary.csv"
)


# ============================================================
# Normalization
# ============================================================
def normalize_doi(value):
    if value is None:
        return ""

    doi = str(value).strip().lower()

    if doi in {"", "nan", "none", "null"}:
        return ""

    doi = re.sub(r"^https?://(dx\.)?doi\.org/", "", doi)
    doi = re.sub(r"^doi:\s*", "", doi)

    return doi.rstrip(" .;,").strip()


def normalize_title(value):
    """
    删除所有非 0-9、a-z、A-Z 的字符。
    空格保留为分隔符，并统一为单个空格。
    """
    if value is None:
        return ""

    title = str(value).strip()

    if title.lower() in {"", "nan", "none", "null"}:
        return ""

    title = re.sub(r"[^0-9A-Za-z]", " ", title)
    title = re.sub(r"\s+", " ", title).strip().lower()

    return title


def clean_value(value):
    if pd.isna(value):
        return None
    return value


def clean_dict(obj):
    if isinstance(obj, dict):
        return {
            key: clean_dict(value)
            for key, value in obj.items()
        }

    if isinstance(obj, list):
        return [clean_dict(value) for value in obj]

    return clean_value(obj)


# ============================================================
# Generic field helpers
# ============================================================
def first_nonempty(row, columns, default=None):
    for column in columns:
        if column not in row:
            continue

        value = row[column]

        if value is None:
            continue

        if isinstance(value, float) and pd.isna(value):
            continue

        if str(value).strip().lower() in {
            "",
            "nan",
            "none",
            "null",
        }:
            continue

        return value

    return default


def get_request_type(row):
    value = first_nonempty(
        row,
        [
            "request_type",
            "query_type",
            "lookup_type",
            "search_type",
            "method",
        ],
    )

    if value is not None:
        value = str(value).lower()

        if "doi" in value:
            return "doi"

        if "title" in value:
            return "title"

    query = first_nonempty(
        row,
        ["query", "search_query", "request_query"],
        "",
    )

    if normalize_doi(query):
        return "doi"

    return "title"


def get_exact_title_match(row):
    value = first_nonempty(
        row,
        [
            "exact_title_match",
            "is_exact_title_match",
            "title_exact_match",
        ],
    )

    return value


def is_false_value(value):
    """
    兼容 False、'False'、'false'、0、'0' 等形式。
    """
    if value is False:
        return True

    if value is None:
        return False

    if isinstance(value, (int, float)):
        return value == 0

    if isinstance(value, str):
        return value.strip().lower() in {
            "false",
            "0",
            "no",
            "not_exact",
            "non_exact",
        }

    return False


# ============================================================
# Abstract reconstruction
# ============================================================
def reconstruct_abstract(inverted_index):
    if not isinstance(inverted_index, dict):
        return ""

    if not inverted_index:
        return ""

    word_positions = []

    for word, positions in inverted_index.items():
        if not isinstance(positions, list):
            continue

        for position in positions:
            try:
                word_positions.append((int(position), word))
            except Exception:
                continue

    word_positions.sort(key=lambda x: x[0])

    return " ".join(
        word for _, word in word_positions
    ).strip()


def get_openalex_record(item):
    """
    兼容不同 JSONL 结构：
    - openalex_record
    - openalex
    - record
    - result
    - item 本身就是 OpenAlex work
    """
    for field in [
        "openalex_record",
        "openalex",
        "record",
        "result",
    ]:
        value = item.get(field)

        if isinstance(value, dict):
            return value

    if isinstance(item.get("id"), str):
        return item

    return {}


def get_abstract(item):
    record = get_openalex_record(item)

    # 1. 优先已有 reconstructed_abstract
    for obj in [item, record]:
        value = obj.get("reconstructed_abstract")

        if isinstance(value, str) and value.strip():
            return re.sub(r"\s+", " ", value).strip()

    # 2. 使用 abstract_inverted_index
    for obj in [item, record]:
        abstract = reconstruct_abstract(
            obj.get("abstract_inverted_index")
        )

        if abstract:
            return re.sub(r"\s+", " ", abstract).strip()

    # 3. 兼容普通 abstract 字段
    for obj in [item, record]:
        value = obj.get("abstract")

        if isinstance(value, str) and value.strip():
            return re.sub(r"\s+", " ", value).strip()

    return ""


def get_openalex_id(item):
    record = get_openalex_record(item)

    return (
        record.get("id")
        or item.get("openalex_id")
        or item.get("id")
        or ""
    )


# ============================================================
# Load CSV metadata
# ============================================================
def load_csv_metadata():
    """
    读取 recovery 目录下的 CSV 文件。
    这些 CSV 提供：
    - request_type/query_type
    - openalex_id
    - exact_title_match
    - query
    - DOI
    - title

    同时读取 coverage 目录下的：
    *_non-main_track_not_in_jsonl.csv
    用于补充完整 dblp_source。
    """
    request_rows = []
    dblp_rows = []

    # recovery 目录中的请求结果 CSV
    recovery_csv_paths = sorted(
        RECOVERY_DIR.glob("*.csv")
    )

    for path in recovery_csv_paths:
        if path.name.endswith(
            "non_main_track_not_in_jsonl.csv"
        ):
            continue

        if path.name in {
            "non_main_track_recovery_with_abstract.csv",
            "non_main_track_recovery_without_abstract.csv",
            "non_main_track_recovery_title_not_exact.csv",
        }:
            continue

        try:
            df = pd.read_csv(path)
        except Exception as exc:
            print(f"[Warning] Cannot read {path}: {exc}")
            continue

        if df.empty:
            continue

        for _, row in df.iterrows():
            record = {
                column: clean_value(row[column])
                for column in df.columns
            }

            record["_source_csv"] = path.name

            doi = first_nonempty(
                record,
                ["doi", "DOI"],
                "",
            )

            title = first_nonempty(
                record,
                ["title", "Title"],
                "",
            )

            openalex_id = first_nonempty(
                record,
                ["openalex_id", "id"],
                "",
            )

            query = first_nonempty(
                record,
                ["query", "search_query"],
                "",
            )

            record["_doi_key"] = normalize_doi(doi)
            record["_title_key"] = normalize_title(title)
            record["_openalex_id_key"] = str(
                openalex_id or ""
            ).strip()
            record["_query_key"] = str(
                query or ""
            ).strip()

            request_rows.append(record)

    # coverage 目录中的 DBLP 缺失记录
    missing_csv_paths = sorted(
        MISSING_DIR.glob(
            "*_non-main_track_not_in_jsonl.csv"
        )
    )

    for path in missing_csv_paths:
        try:
            df = pd.read_csv(path)
        except Exception as exc:
            print(f"[Warning] Cannot read {path}: {exc}")
            continue

        if df.empty:
            continue

        if "conference" not in df.columns:
            conference = path.name.split(
                "_non-main_track"
            )[0].upper()
            df["conference"] = conference

        for _, row in df.iterrows():
            record = {
                column: clean_value(row[column])
                for column in df.columns
            }

            record["_source_csv"] = path.name

            doi = first_nonempty(
                record,
                ["doi", "DOI"],
                "",
            )

            title = first_nonempty(
                record,
                ["title", "Title"],
                "",
            )

            record["_doi_key"] = normalize_doi(doi)
            record["_title_key"] = normalize_title(title)

            dblp_rows.append(record)

    # 请求结果索引
    request_indexes = {
        "openalex_id": {},
        "doi": {},
        "title": {},
        "query": {},
    }

    for record in request_rows:
        if record["_openalex_id_key"]:
            request_indexes["openalex_id"].setdefault(
                record["_openalex_id_key"],
                record,
            )

        if record["_doi_key"]:
            request_indexes["doi"].setdefault(
                record["_doi_key"],
                record,
            )

        if record["_title_key"]:
            request_indexes["title"].setdefault(
                record["_title_key"],
                record,
            )

        if record["_query_key"]:
            request_indexes["query"].setdefault(
                record["_query_key"],
                record,
            )

    # DBLP 索引
    dblp_indexes = {
        "doi": {},
        "title": {},
    }

    for record in dblp_rows:
        if record["_doi_key"]:
            dblp_indexes["doi"].setdefault(
                record["_doi_key"],
                record,
            )

        if record["_title_key"]:
            dblp_indexes["title"].setdefault(
                record["_title_key"],
                record,
            )

    return request_indexes, dblp_indexes


request_indexes, dblp_indexes = load_csv_metadata()


# ============================================================
# Match CSV metadata to JSONL record
# ============================================================
def get_item_metadata(item):
    record = get_openalex_record(item)

    source_row = item.get("source_row")
    if not isinstance(source_row, dict):
        source_row = item.get("original_row")

    if not isinstance(source_row, dict):
        source_row = {}

    openalex_id = (
        record.get("id")
        or item.get("openalex_id")
        or item.get("id")
        or ""
    )

    doi = (
        item.get("doi")
        or source_row.get("doi")
        or record.get("doi")
        or ""
    )

    title = (
        item.get("title")
        or source_row.get("title")
        or record.get("title")
        or record.get("display_name")
        or ""
    )

    query = (
        item.get("query")
        or source_row.get("query")
        or ""
    )

    return {
        "openalex_id": str(openalex_id).strip(),
        "doi": doi,
        "title": title,
        "query": str(query).strip(),
    }


def match_csv_metadata(item):
    metadata = get_item_metadata(item)

    openalex_id = metadata["openalex_id"]
    doi_key = normalize_doi(metadata["doi"])
    title_key = normalize_title(metadata["title"])
    query_key = metadata["query"]

    if (
        openalex_id
        and openalex_id in request_indexes["openalex_id"]
    ):
        return request_indexes["openalex_id"][openalex_id]

    if doi_key and doi_key in request_indexes["doi"]:
        return request_indexes["doi"][doi_key]

    if query_key and query_key in request_indexes["query"]:
        return request_indexes["query"][query_key]

    if title_key and title_key in request_indexes["title"]:
        return request_indexes["title"][title_key]

    return {}


# ============================================================
# Match complete DBLP source
# ============================================================
def match_dblp_source(item, csv_metadata):
    metadata = get_item_metadata(item)

    doi = (
        csv_metadata.get("doi")
        or metadata.get("doi")
    )

    title = (
        csv_metadata.get("title")
        or metadata.get("title")
    )

    doi_key = normalize_doi(doi)
    title_key = normalize_title(title)

    # DOI 优先
    if doi_key and doi_key in dblp_indexes["doi"]:
        source = dict(dblp_indexes["doi"][doi_key])

    # DOI 失败后使用 title
    elif title_key and title_key in dblp_indexes["title"]:
        source = dict(dblp_indexes["title"][title_key])

    else:
        source = {}

    # 删除内部索引字段
    source.pop("_doi_key", None)
    source.pop("_title_key", None)
    source.pop("_source_csv", None)

    return clean_dict(source)


def is_complete_dblp_source(source):
    required_fields = [
        "conference",
        "year",
        "title",
        "proceedings_type",
        "proceedings_name",
        "track_type",
        "section/track_name",
    ]

    return (
        isinstance(source, dict)
        and all(
            source.get(field) not in {
                None,
                "",
                "nan",
                "None",
            }
            for field in required_fields
        )
    )


# ============================================================
# Build output record
# ============================================================
def build_output_record(
    item,
    csv_metadata,
    dblp_source,
    abstract,
):
    openalex_record = get_openalex_record(item)

    if openalex_record:
        output = dict(openalex_record)
    else:
        output = dict(item)

        for field in [
            "openalex_record",
            "openalex",
            "record",
            "result",
        ]:
            output.pop(field, None)

    # 保留请求相关信息
    for field in [
        "request_type",
        "query_type",
        "query",
        "method",
        "openalex_id",
        "exact_title_match",
    ]:
        if field in csv_metadata:
            output[field] = csv_metadata[field]
        elif field in item:
            output[field] = item[field]

    # 添加摘要
    if abstract:
        output["reconstructed_abstract"] = abstract
    else:
        output.pop("reconstructed_abstract", None)

    # 添加完整 DBLP source
    output["dblp_source"] = dblp_source

    return clean_dict(output)


# ============================================================
# Deduplicate
# ============================================================
def get_dedup_key(item):
    openalex_id = get_openalex_id(item)

    if openalex_id:
        return f"id::{openalex_id}"

    source = item.get("dblp_source") or {}

    doi = normalize_doi(source.get("doi"))

    if doi:
        return f"doi::{doi}"

    title = normalize_title(source.get("title"))
    conference = str(
        source.get("conference") or ""
    ).lower()

    year = str(source.get("year") or "")

    return (
        f"title::{conference}::{year}::{title}"
    )


def deduplicate_records(records):
    result = {}

    for item in records:
        result[get_dedup_key(item)] = item

    return list(result.values())


# ============================================================
# Read JSONL and classify
# ============================================================
with_abstract = []
without_abstract = []
title_not_exact = []

stats = {
    "total_input_records": 0,
    "doi_with_abstract": 0,
    "title_exact_with_abstract": 0,
    "doi_without_abstract": 0,
    "title_exact_without_abstract": 0,
    "title_not_exact": 0,
    "missing_or_incomplete_dblp_source": 0,
    "csv_metadata_not_found": 0,
}


jsonl_paths = sorted(
    RECOVERY_DIR.glob("*.jsonl")
)

if not jsonl_paths:
    raise FileNotFoundError(
        f"No JSONL files found in {RECOVERY_DIR}"
    )


for jsonl_path in tqdm(
    jsonl_paths,
    desc="Processing recovery JSONL files",
):
    with open(jsonl_path, "r", encoding="utf-8") as f:
        for line_number, line in enumerate(
            f,
            start=1,
        ):
            line = line.strip()

            if not line:
                continue

            stats["total_input_records"] += 1

            try:
                item = json.loads(line)
            except json.JSONDecodeError as exc:
                print(
                    f"[Warning] Invalid JSON: "
                    f"{jsonl_path.name}:{line_number}: {exc}"
                )
                continue

            csv_metadata = match_csv_metadata(item)

            if not csv_metadata:
                stats["csv_metadata_not_found"] += 1

            request_type = get_request_type(
                csv_metadata or item
            )

            exact_title_match = get_exact_title_match(
                csv_metadata or item
            )

            abstract = get_abstract(item)

            # title 非精确匹配
            if (
                request_type == "title"
                and is_false_value(exact_title_match)
            ):
                metadata = get_item_metadata(item)

                title_not_exact.append({
                    "source_file": jsonl_path.name,
                    "line_number": line_number,
                    "request_type": request_type,
                    "exact_title_match": exact_title_match,
                    "openalex_id": metadata[
                        "openalex_id"
                    ],
                    "doi": metadata["doi"],
                    "title": metadata["title"],
                    "query": metadata["query"],
                    "raw_record": json.dumps(
                        item,
                        ensure_ascii=False,
                    ),
                })

                stats["title_not_exact"] += 1
                continue

            dblp_source = match_dblp_source(
                item,
                csv_metadata,
            )

            if not is_complete_dblp_source(
                dblp_source
            ):
                stats[
                    "missing_or_incomplete_dblp_source"
                ] += 1

            output = build_output_record(
                item=item,
                csv_metadata=csv_metadata,
                dblp_source=dblp_source,
                abstract=abstract,
            )

            # DOI 请求
            if request_type == "doi":
                if abstract:
                    with_abstract.append(output)
                    stats["doi_with_abstract"] += 1
                else:
                    without_abstract.append(output)
                    stats["doi_without_abstract"] += 1

            # title 请求
            elif request_type == "title":
                if not is_false_value(
                    exact_title_match
                ):
                    if abstract:
                        with_abstract.append(output)
                        stats[
                            "title_exact_with_abstract"
                        ] += 1
                    else:
                        without_abstract.append(output)
                        stats[
                            "title_exact_without_abstract"
                        ] += 1


# ============================================================
# Deduplicate
# ============================================================
with_abstract = deduplicate_records(
    with_abstract
)

without_abstract = deduplicate_records(
    without_abstract
)


# ============================================================
# Write JSONL
# ============================================================
def write_jsonl(path, records):
    with open(path, "w", encoding="utf-8") as f:
        for item in records:
            f.write(
                json.dumps(
                    item,
                    ensure_ascii=False,
                )
                + "\n"
            )


write_jsonl(
    WITH_ABSTRACT_PATH,
    with_abstract,
)

write_jsonl(
    WITHOUT_ABSTRACT_PATH,
    without_abstract,
)


# ============================================================
# Write title non-exact CSV
# ============================================================
pd.DataFrame(title_not_exact).to_csv(
    TITLE_NOT_EXACT_PATH,
    index=False,
    encoding="utf-8-sig",
)


# ============================================================
# Summary
# ============================================================
summary_rows = [
    {
        "metric": key,
        "value": value,
    }
    for key, value in stats.items()
]

summary_rows.extend([
    {
        "metric": "final_with_abstract_after_dedup",
        "value": len(with_abstract),
    },
    {
        "metric": "final_without_abstract_after_dedup",
        "value": len(without_abstract),
    },
    {
        "metric": "final_title_not_exact",
        "value": len(title_not_exact),
    },
])

pd.DataFrame(summary_rows).to_csv(
    SUMMARY_PATH,
    index=False,
    encoding="utf-8-sig",
)


# ============================================================
# Group summary
# ============================================================
def records_to_group_df(records, output_type):
    rows = []

    for item in records:
        source = item.get("dblp_source") or {}

        rows.append({
            "output_type": output_type,
            "conference": source.get("conference"),
            "year": source.get("year"),
            "proceedings_type": source.get(
                "proceedings_type"
            ),
            "proceedings_name": source.get(
                "proceedings_name"
            ),
            "track_type": source.get(
                "track_type"
            ),
            "section/track_name": source.get(
                "section/track_name"
            ),
        })

    return pd.DataFrame(rows)


group_frames = []

if with_abstract:
    group_frames.append(
        records_to_group_df(
            with_abstract,
            "with_abstract",
        )
    )

if without_abstract:
    group_frames.append(
        records_to_group_df(
            without_abstract,
            "without_abstract",
        )
    )

if group_frames:
    group_df = pd.concat(
        group_frames,
        ignore_index=True,
    )

    group_summary = (
        group_df
        .groupby(
            [
                "output_type",
                "conference",
                "year",
                "proceedings_type",
                "proceedings_name",
                "track_type",
                "section/track_name",
            ],
            dropna=False,
        )
        .size()
        .reset_index(name="n_records")
        .sort_values(
            [
                "output_type",
                "conference",
                "year",
                "proceedings_type",
                "proceedings_name",
                "track_type",
                "section/track_name",
            ]
        )
    )
else:
    group_summary = pd.DataFrame()


group_summary.to_csv(
    GROUP_SUMMARY_PATH,
    index=False,
    encoding="utf-8-sig",
)


# ============================================================
# Print summary
# ============================================================
print("\nProcessing completed.")
print(f"Input records: {stats['total_input_records']}")
print(
    "CSV metadata not found: "
    f"{stats['csv_metadata_not_found']}"
)
print(
    "DOI requests with abstract: "
    f"{stats['doi_with_abstract']}"
)
print(
    "Title exact matches with abstract: "
    f"{stats['title_exact_with_abstract']}"
)
print(
    "DOI requests without abstract: "
    f"{stats['doi_without_abstract']}"
)
print(
    "Title exact matches without abstract: "
    f"{stats['title_exact_without_abstract']}"
)
print(
    "Title non-exact matches: "
    f"{stats['title_not_exact']}"
)
print(
    "Missing or incomplete dblp_source: "
    f"{stats['missing_or_incomplete_dblp_source']}"
)

print("\nSaved files:")
print(WITH_ABSTRACT_PATH)
print(WITHOUT_ABSTRACT_PATH)
print(TITLE_NOT_EXACT_PATH)
print(SUMMARY_PATH)
print(GROUP_SUMMARY_PATH)

Processing recovery JSONL files: 100%|██████████| 8/8 [00:00<00:00, 19.14it/s]

Processing completed.
Input records: 586
CSV metadata not found: 0
DOI requests with abstract: 0
Title exact matches with abstract: 96
DOI requests without abstract: 218
Title exact matches without abstract: 84
Title non-exact matches: 188
Missing or incomplete dblp_source: 398

Saved files:
/home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260716_openalex_non_main_track_doi_title_recovery/classified_results/non_main_track_recovery_with_abstract.jsonl
/home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260716_openalex_non_main_track_doi_title_recovery/classified_results/non_main_track_recovery_without_abstract.jsonl
/home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260716_openalex_non_main_track_doi_title_recovery/classified_results/non_main_track_recovery_title_not_exact.csv
/home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260716_openalex_non_main_track_doi_title_recovery/classified_results/recovery_summary.csv
/home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260716_openalex_non_main_track_doi_title_recovery/classified_results/recovery_group_summary.csv

In [15]:
import json
import re
import shutil
from pathlib import Path

import pandas as pd
from tqdm import tqdm


# ============================================================
# Paths
# ============================================================
PROJECT_ROOT = Path(
    "/home/user/GSK/lily/science_of_science/NewDataset/"
    "AI_impact_on_cs_publications"
)

RECOVERY_DIR = (
    PROJECT_ROOT
    / "Data/20260716_openalex_non_main_track_doi_title_recovery"
)

CLASSIFIED_DIR = RECOVERY_DIR / "classified_results"

WITHOUT_ABSTRACT_PATH = (
    CLASSIFIED_DIR
    / "non_main_track_recovery_without_abstract.jsonl"
)

WITH_ABSTRACT_PATH = (
    CLASSIFIED_DIR
    / "non_main_track_recovery_with_abstract.jsonl"
)

REPORT_DIR = RECOVERY_DIR
DBLP_DIR = PROJECT_ROOT / "Data/20260706_dblp"

OUT_DIR = CLASSIFIED_DIR / "dblp_enriched"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OUT_WITHOUT_ABSTRACT = (
    OUT_DIR
    / "non_main_track_recovery_without_abstract_dblp_enriched.jsonl"
)

OUT_WITH_ABSTRACT = (
    OUT_DIR
    / "non_main_track_recovery_with_abstract_dblp_enriched.jsonl"
)

UNMATCHED_CSV = (
    OUT_DIR
    / "non_main_track_recovery_dblp_unmatched.csv"
)

SUMMARY_CSV = (
    OUT_DIR
    / "non_main_track_recovery_dblp_match_summary.csv"
)


# ============================================================
# Normalization
# ============================================================
def normalize_doi(value):
    if value is None:
        return ""

    doi = str(value).strip().lower()

    if doi in {"", "nan", "none", "null"}:
        return ""

    doi = re.sub(r"^https?://(dx\.)?doi\.org/", "", doi)
    doi = re.sub(r"^doi:\s*", "", doi)

    return doi.rstrip(" .;,").strip()


def normalize_title(value):
    """
    删除所有非 0-9、a-z、A-Z 的字符，
    空格保留并统一为单个空格。
    """
    if value is None:
        return ""

    title = str(value).strip()

    if title.lower() in {"", "nan", "none", "null"}:
        return ""

    title = re.sub(r"[^0-9A-Za-z]", " ", title)
    title = re.sub(r"\s+", " ", title).strip().lower()

    return title


def clean_value(value):
    if pd.isna(value):
        return None
    return value


def clean_dict(obj):
    if isinstance(obj, dict):
        return {
            key: clean_dict(value)
            for key, value in obj.items()
        }

    if isinstance(obj, list):
        return [
            clean_dict(value)
            for value in obj
        ]

    return clean_value(obj)


# ============================================================
# JSONL helpers
# ============================================================
def read_jsonl(path):
    records = []

    with open(path, "r", encoding="utf-8") as f:
        for line_number, line in enumerate(f, start=1):
            line = line.strip()

            if not line:
                continue

            try:
                records.append(json.loads(line))
            except json.JSONDecodeError as exc:
                print(
                    f"[Warning] Invalid JSON: "
                    f"{path.name}:{line_number} | {exc}"
                )

    return records


def write_jsonl(path, records):
    with open(path, "w", encoding="utf-8") as f:
        for record in records:
            f.write(
                json.dumps(
                    clean_dict(record),
                    ensure_ascii=False,
                )
                + "\n"
            )


# ============================================================
# Generic helpers
# ============================================================
def first_existing(row, columns, default=None):
    for column in columns:
        if column not in row:
            continue

        value = row[column]

        if value is None:
            continue

        if str(value).strip().lower() in {
            "",
            "nan",
            "none",
            "null",
        }:
            continue

        return value

    return default


def get_openalex_record(item):
    for field in [
        "openalex_record",
        "openalex",
        "record",
        "result",
    ]:
        value = item.get(field)

        if isinstance(value, dict):
            return value

    if isinstance(item.get("id"), str):
        return item

    return {}


# ============================================================
# Step 1: Merge OpenAlex recovery report CSV files
# ============================================================
report_paths = sorted(
    REPORT_DIR.glob(
        "*_non_main_track_openalex_recovery_report.csv"
    )
)

if not report_paths:
    raise FileNotFoundError(
        "No *_non_main_track_openalex_recovery_report.csv files found."
    )

report_frames = []

for path in report_paths:
    df = pd.read_csv(path)

    if df.empty:
        continue

    df["_report_source"] = path.name
    report_frames.append(df)


if not report_frames:
    raise RuntimeError("All recovery report CSV files are empty.")

report_df = pd.concat(
    report_frames,
    ignore_index=True,
)

# 统一 OpenAlex ID 字段
if "openalex_id" not in report_df.columns:
    for candidate in ["id", "openalex", "openalex_work_id"]:
        if candidate in report_df.columns:
            report_df["openalex_id"] = report_df[candidate]
            break

if "openalex_id" not in report_df.columns:
    raise ValueError(
        "No openalex_id/id column found in recovery reports."
    )

report_df["openalex_id"] = (
    report_df["openalex_id"]
    .fillna("")
    .astype(str)
    .str.strip()
)

report_df["doi_key"] = report_df.apply(
    lambda row: normalize_doi(
        first_existing(row, ["doi", "DOI"], "")
    ),
    axis=1,
)

report_df["title_key"] = report_df.apply(
    lambda row: normalize_title(
        first_existing(row, ["title", "Title"], "")
    ),
    axis=1,
)

report_df = report_df.drop_duplicates(
    subset=["openalex_id"],
    keep="first",
)

report_by_id = {
    row["openalex_id"]: row.to_dict()
    for _, row in report_df.iterrows()
    if row["openalex_id"]
}

print(f"Merged recovery report rows: {len(report_df)}")


# ============================================================
# Step 2: Read DBLP files and build indexes
# ============================================================
dblp_paths = sorted(
    DBLP_DIR.glob("*_dblp_2020_2025_all_tracks.csv")
)

if not dblp_paths:
    raise FileNotFoundError(
        f"No DBLP CSV files found in {DBLP_DIR}"
    )

dblp_frames = []

for path in dblp_paths:
    df = pd.read_csv(path)

    if df.empty:
        continue

    if "conference" not in df.columns:
        conference = path.name.split("_dblp_")[0].upper()
        df["conference"] = conference

    dblp_frames.append(df)


dblp_df = pd.concat(
    dblp_frames,
    ignore_index=True,
)

dblp_df["doi_key"] = dblp_df["doi"].map(
    normalize_doi
)

dblp_df["title_key"] = dblp_df["title"].map(
    normalize_title
)

dblp_by_doi = {}
dblp_by_title = {}

for _, row in dblp_df.iterrows():
    record = {
        column: clean_value(row[column])
        for column in dblp_df.columns
        if column not in {"doi_key", "title_key"}
    }

    doi_key = row["doi_key"]
    title_key = row["title_key"]

    if doi_key:
        dblp_by_doi.setdefault(doi_key, []).append(record)

    if title_key:
        dblp_by_title.setdefault(title_key, []).append(record)


# ============================================================
# Step 3: Match report metadata to DBLP
# ============================================================
def get_jsonl_metadata(item, report_row):
    record = get_openalex_record(item)

    openalex_id = (
        item.get("id")
        or item.get("openalex_id")
        or record.get("id")
        or ""
    )

    doi = (
        report_row.get("doi")
        or item.get("doi")
        or record.get("doi")
        or ""
    )

    title = (
        report_row.get("title")
        or item.get("title")
        or record.get("title")
        or record.get("display_name")
        or ""
    )

    conference = (
        report_row.get("conference")
        or report_row.get("Conference")
        or ""
    )

    year = (
        report_row.get("year")
        or report_row.get("Year")
        or ""
    )

    return {
        "openalex_id": str(openalex_id).strip(),
        "doi": doi,
        "title": title,
        "conference": str(conference).strip(),
        "year": str(year).strip(),
    }


def filter_by_conference_year(
    candidates,
    conference,
    year,
):
    if not candidates:
        return []

    filtered = candidates

    if conference:
        same_conference = [
            record
            for record in candidates
            if str(record.get("conference", "")).strip().lower()
            == conference.strip().lower()
        ]

        if same_conference:
            filtered = same_conference

    if year and year.lower() not in {"nan", "none", ""}:
        try:
            year_int = int(float(year))

            same_year = [
                record
                for record in filtered
                if str(record.get("year", "")).strip()
                == str(year_int)
            ]

            if same_year:
                filtered = same_year

        except ValueError:
            pass

    return filtered


def match_dblp_record(item, report_row):
    metadata = get_jsonl_metadata(item, report_row)

    conference = metadata["conference"]
    year = metadata["year"]

    doi_key = normalize_doi(metadata["doi"])
    title_key = normalize_title(metadata["title"])

    # DOI 优先
    if doi_key and doi_key in dblp_by_doi:
        candidates = filter_by_conference_year(
            dblp_by_doi[doi_key],
            conference,
            year,
        )

        if len(candidates) == 1:
            return candidates[0], "doi"

        if len(candidates) > 1:
            return candidates[0], "doi_multiple"

    # DOI 未匹配时使用标题
    if title_key and title_key in dblp_by_title:
        candidates = filter_by_conference_year(
            dblp_by_title[title_key],
            conference,
            year,
        )

        if len(candidates) == 1:
            return candidates[0], "title"

        if len(candidates) > 1:
            return candidates[0], "title_multiple"

    return None, "unmatched"


# ============================================================
# Step 4: Process JSONL files
# ============================================================
def process_jsonl(input_path, output_path):
    records = read_jsonl(input_path)

    enriched_records = []
    unmatched_rows = []
    match_counts = {}

    for item in tqdm(
        records,
        desc=f"Matching {input_path.name}",
    ):
        openalex_id = str(
            item.get("id")
            or item.get("openalex_id")
            or get_openalex_record(item).get("id")
            or ""
        ).strip()

        # 先通过 OpenAlex ID 找 report CSV 记录
        report_row = report_by_id.get(openalex_id)

        if report_row is None:
            unmatched_rows.append({
                "source_file": input_path.name,
                "openalex_id": openalex_id,
                "conference": "",
                "year": "",
                "title": "",
                "doi": "",
                "match_stage": "report_csv",
                "reason": "openalex_id_not_found_in_report_csv",
            })
            match_counts["report_id_not_found"] = (
                match_counts.get(
                    "report_id_not_found",
                    0,
                )
                + 1
            )
            continue

        dblp_record, match_method = match_dblp_record(
            item,
            report_row,
        )

        if dblp_record is None:
            metadata = get_jsonl_metadata(
                item,
                report_row,
            )

            unmatched_rows.append({
                "source_file": input_path.name,
                "openalex_id": metadata["openalex_id"],
                "conference": metadata["conference"],
                "year": metadata["year"],
                "title": metadata["title"],
                "doi": metadata["doi"],
                "match_stage": "dblp",
                "reason": "doi_and_title_not_found",
            })

            match_counts["dblp_unmatched"] = (
                match_counts.get(
                    "dblp_unmatched",
                    0,
                )
                + 1
            )
            continue

        # 补充完整 dblp_source
        output_item = dict(item)
        output_item["dblp_source"] = clean_dict(
            dblp_record
        )

        enriched_records.append(output_item)

        match_counts[match_method] = (
            match_counts.get(match_method, 0)
            + 1
        )

    write_jsonl(
        output_path,
        enriched_records,
    )

    return (
        enriched_records,
        unmatched_rows,
        match_counts,
    )


# ============================================================
# Run
# ============================================================
all_unmatched = []
summary_rows = []

for input_path, output_path in [
    (
        WITHOUT_ABSTRACT_PATH,
        OUT_WITHOUT_ABSTRACT,
    ),
    (
        WITH_ABSTRACT_PATH,
        OUT_WITH_ABSTRACT,
    ),
]:
    if not input_path.exists():
        print(f"[Warning] Missing file: {input_path}")
        continue

    enriched, unmatched, counts = process_jsonl(
        input_path,
        output_path,
    )

    all_unmatched.extend(unmatched)

    summary_rows.append({
        "input_file": input_path.name,
        "output_file": output_path.name,
        "input_records": len(read_jsonl(input_path)),
        "matched_records": len(enriched),
        "unmatched_records": len(unmatched),
        **counts,
    })


# ============================================================
# Save unmatched records and summary
# ============================================================
pd.DataFrame(all_unmatched).to_csv(
    UNMATCHED_CSV,
    index=False,
    encoding="utf-8-sig",
)

pd.DataFrame(summary_rows).to_csv(
    SUMMARY_CSV,
    index=False,
    encoding="utf-8-sig",
)


print("\nProcessing completed.")
print(f"DBLP files loaded: {len(dblp_paths)}")
print(f"Recovery reports loaded: {len(report_paths)}")
print(f"Unmatched records: {len(all_unmatched)}")
print(f"Saved: {OUT_WITHOUT_ABSTRACT}")
print(f"Saved: {OUT_WITH_ABSTRACT}")
print(f"Saved: {UNMATCHED_CSV}")
print(f"Saved: {SUMMARY_CSV}")

Merged recovery report rows: 577

Matching non_main_track_recovery_without_abstract.jsonl: 100%|██████████| 302/302 [00:00<00:00, 2829.60it/s]
Matching non_main_track_recovery_with_abstract.jsonl: 100%|██████████| 96/96 [00:00<00:00, 37008.56it/s]

Processing completed.
DBLP files loaded: 10
Recovery reports loaded: 8
Unmatched records: 0
Saved: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260716_openalex_non_main_track_doi_title_recovery/classified_results/dblp_enriched/non_main_track_recovery_without_abstract_dblp_enriched.jsonl
Saved: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260716_openalex_non_main_track_doi_title_recovery/classified_results/dblp_enriched/non_main_track_recovery_with_abstract_dblp_enriched.jsonl
Saved: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260716_openalex_non_main_track_doi_title_recovery/classified_results/dblp_enriched/non_main_track_recovery_dblp_unmatched.csv
Saved: /home/user/GSK/lily/science_of_science/NewDataset/AI_impact_on_cs_publications/Data/20260716_openalex_non_main_track_doi_title_recovery/classified_results/dblp_enriched/non_main_track_recovery_dblp_match_summary.csv